Repository ansible/ansible-navigator, pull requests merged in 2021-08, with the labels that each got.

#540 Fix the CI failures with linting and outdated EE image
  ansible_navigator/configuration_subsystem/navigator_configuration.py
  docs/settings.rst
  test-requirements.txt
  tests/defaults.py
  tests/fixtures/unit/cli/ansible-navigator.yml
  tests/unit/test_cli.py
  tox.ini
Labels: gate, tests, bug

#534 Use `extend-` versions of the flake8 options
  tox.ini
Labels: enhancement, gate, tests

#535 Add text descriptions to all tox envs
  tox.ini
Labels: enhancement, gate

#536 Add initial docs infra
  .readthedocs.yml
  README.md
  ansible_navigator/__main__.py
  ansible_navigator/actions/inventory.py
  ansible_navigator/actions/run.py
  ansible_navigator/app.py
  ansible_navigator/cli.py
  ansible_navigator/runner/api.py
  ansible_navigator/steps.py
  ansible_navigator/ui_framework/colorize.py
  ansible_navigator/ui_framework/menu_builder.py
  ansible_navigator/ui_framework/ui.py
  ansible_navigator/ui_framework/utils.py
  ansible_navigator/utils.py
  docs/conf.py
  docs/faq.md
  docs/index.md
  docs/index.rst
  docs/installing.rst
  docs/pkg/.gitignore
  docs/requirements.in
  docs/settings.rst
  docs/subcommands.rst
  docs/user_guide/index.rst
  tox.ini
  utilities/doc_updater.py
Labels: documentation, gate

#542 [yaml] remove explicit sort_keys
  ansible_navigator/yaml.py
Labels: gate

#544 Add labels to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/security_bug_report.md
Labels: enhancement, gate
