Repository ansible/ansible-navigator, pull requests merged in 2021-09, with the labels that each got.

#552 Clean up the outdated docs
  docs/cli_reference/ansible_navigator.rst
  docs/cli_reference/index.rst
  docs/cli_reference/tui_mode.rst
  docs/index.md
  docs/installing.rst
  docs/user_guide/explore_content.rst
  docs/user_guide/index.rst
  docs/user_guide/manage_inventory.rst
  docs/user_guide/overview.rst
  docs/user_guide/run_playbooks.rst
  docs/user_guide/using_docs.rst
Labels: documentation, gate, new

#563 Refactor inventory details collection to reduce branches and locals
  ansible_navigator/actions/inventory.py
Labels: gate

#564 Move `doc_updater` under `docs/`
  docs/_ext/single_sourced_data.py
  docs/conf.py
  docs/settings.rst
  docs/subcommands.rst
  tox.ini
  utilities/doc_updater.py
Labels: documentation, tests, structural

#511 Add support for container-options
  ansible_navigator/actions/collections.py
  ansible_navigator/actions/config.py
  ansible_navigator/actions/doc.py
  ansible_navigator/actions/images.py
  ansible_navigator/actions/inventory.py
  ansible_navigator/actions/run.py
  ansible_navigator/configuration_subsystem/navigator_configuration.py
  ansible_navigator/configuration_subsystem/navigator_post_processor.py
  ansible_navigator/runner/api.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/_action_run_test.py
  tests/unit/actions/test_run.py
  tests/unit/configuration_subsystem/data.py
Labels: enhancement, gate, research

#571 Restore zuul jobs
  .zuul.d/jobs.yaml
  .zuul.d/project.yaml
  bindep.txt
  tools/test-setup.sh
Labels: gate, skip-changelog

#543 Revert "Drop `{tty}` and `{temp_dir}` substitutions"
  tox.ini
Labels: gate

#575 [utils] Fix share dir when running from repo clone
  src/ansible_navigator/utils.py
Labels: gate

#576 [yaml] Rename yaml to _yaml to prevent conflicts
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/ui_framework/ui.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
  tests/unit/test_yaml.py
  tests/unit/ui_framework/test_colorize.py
Labels: gate

#567 Add ansible-related extras to distribution package
  README.md
  setup.cfg
Labels: documentation, enhancement, gate

#578 Note use of stdout for vars prompt in the FAQ
  docs/faq.md
Labels: gate

#581 Add FAQ entry for ssh keys
  docs/faq.md
Labels: gate

#583 Correct FAQ formatting
  docs/faq.md
Labels: gate
