Repository ansible/ansible-navigator, pull requests merged in 2021-12, with the labels that each got.

#635 [linting, tests] Type hinting clean up
  src/ansible_navigator/py.typed
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/utils.py
  tests/unit/test_utils.py
Labels: gate, skip-changelog

#642 [linters] Missing space for type ignore
  src/ansible_navigator/runner/ansible_config.py
Labels: gate, skip-changelog

#644 [tests] Fix pylint errors in `tests/unit`
  tests/defaults.py
  tests/unit/actions/test_config.py
  tests/unit/actions/test_inventory.py
  tests/unit/actions/test_run.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_container_engine_auto.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
  tests/unit/configuration_subsystem/utils.py
  tests/unit/test_cli.py
  tests/unit/test_image_introspection.py
  tests/unit/test_log_append.py
  tests/unit/test_yaml.py
Labels: gate, skip-changelog

#639 [typing] Clarify some type ignores, remove uneeded
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/tm_tokenize/reg.py
  src/ansible_navigator/tm_tokenize/utils.py
  src/ansible_navigator/ui_framework/form_handler_text.py
Labels: gate, skip-changelog

#645 [tests] Fix pylint errors in `tests/fixtures`
  tests/fixtures/common/collections/ansible_collections/testorg/coll_1/plugins/lookup/lookup_1.py
  tests/fixtures/common/collections/ansible_collections/testorg/coll_1/plugins/modules/mod_1.py
  tests/fixtures/common/collections/ansible_collections/testorg/coll_2/plugins/lookup/lookup_2.py
  tests/fixtures/common/collections/ansible_collections/testorg/coll_2/plugins/modules/mod_2.py
Labels: gate, skip-changelog

#637 [linting] Switch to f strings from format
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils.py
Labels: gate, skip-changelog

#605 change default execution environment image
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  tests/defaults.py
  tests/fixtures/unit/cli/ansible-navigator.yml
  tests/unit/test_cli.py
  tox.ini
Labels: enhancement, gate

#655 Integrate linters through pre-commit.com tool
  .github/chronographer.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  docs/_ext/spelling_stub_ext.py
  docs/changelog-fragments.d/.CHANGELOG-TEMPLATE.md.j2
  docs/changelog-fragments.d/.gitignore
  docs/changelog-fragments.d/558.misc.md
  docs/changelog-fragments.d/654.misc.md
  docs/changelog-fragments.d/655.internal.md
  docs/changelog-fragments.d/README.md
  docs/changelog.md
  docs/conf.py
  docs/index.md
  docs/requirements.in
  pyproject.toml
  tox.ini
Labels: gate, tests, structural, bot:chronographer:provided

#658 Exclude change note fragments in markdownlint
  .pre-commit-config.yaml
Labels: gate, tests, skip-changelog, bot:chronographer:skip

#659 Only run flake8 on manual invocations
  .pre-commit-config.yaml
Labels: gate, tests, skip-changelog, bot:chronographer:skip

#653 Reinstate linters zuul job
  .zuul.d/jobs.yaml
  .zuul.d/project.yaml
Labels: skip-changelog, bot:chronographer:skip

#665 Fix linting regressions
  docs/_ext/spelling_stub_ext.py
  src/ansible_navigator/utils.py
Labels: skip-changelog, bot:chronographer:skip

#666 Fix typing in `setup` of Sphinx spelling stub ext
  docs/_ext/spelling_stub_ext.py
Labels: tests, new, skip-changelog, bot:chronographer:skip

#669 Fix typing in the `single_sourced_data` Sphinx ext
  docs/_ext/single_sourced_data.py
Labels: gate, tests, new, skip-changelog, bot:chronographer:skip

#663 [tests] Update 2 periodically failing tests
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/5.json
  tests/integration/actions/inventory/test_stdout_tmux.py
  tests/integration/actions/templar/base.py
Labels: tests, skip-changelog, bot:chronographer:skip

#668 Move slow flake8 plugins to run manually
  .pre-commit-config.yaml
  docs/changelog-fragments.d/668.internal.md
Labels: gate, skip-changelog, bot:chronographer:provided

#670 [type] Ignore attr defined
  src/ansible_navigator/actions/_actions.py
Labels: gate, skip-changelog, bot:chronographer:skip

#672 [tests, lint] Add missing comma
  tests/integration/actions/templar/base.py
Labels: skip-changelog, bot:chronographer:skip, impatience-allowed

#651 [lint, type] Linting, docstring and type improvements in `_` files
  docs/conf.py
  src/ansible_navigator/__init__.py
  src/ansible_navigator/_version.py
  src/ansible_navigator/_yaml.py
Labels: gate, skip-changelog, bot:chronographer:skip

#673 [lint] long line
  src/ansible_navigator/_yaml.py
Labels: skip-changelog, bot:chronographer:skip

#671 Make linting job voting
  .zuul.d/jobs.yaml
Labels: gate, skip-changelog, bot:chronographer:skip, impatience-allowed

#652 [lint, type] Linting, docstring and type improvements in a*.py files
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/app.py
  src/ansible_navigator/app_public.py
Labels: gate, skip-changelog, bot:chronographer:skip

#648 [tests] Fix pylint errors in `tests/interactive`
  tests/integration/_action_run_test.py
  tests/integration/_common.py
  tests/integration/_interactions.py
  tests/integration/_tmux_session.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/collections/test_direct_interactive_ee.py
  tests/integration/actions/collections/test_direct_interactive_noee.py
  tests/integration/actions/collections/test_welcome_interactive_ee.py
  tests/integration/actions/collections/test_welcome_interactive_noee.py
  tests/integration/actions/config/base.py
  tests/integration/actions/config/test_direct_interactive_ee.py
  tests/integration/actions/config/test_direct_interactive_noee.py
  tests/integration/actions/config/test_stdout_tmux.py
  tests/integration/actions/config/test_welcome_interactive_ee.py
  tests/integration/actions/config/test_welcome_interactive_noee.py
  tests/integration/actions/config/test_welcome_interactive_param_use.py
  tests/integration/actions/config/test_welcome_interactive_specified_config.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/doc/test_direct_interactive_ee.py
  tests/integration/actions/doc/test_direct_interactive_noee.py
  tests/integration/actions/doc/test_stdout.py
  tests/integration/actions/doc/test_welcome_interactive_ee.py
  tests/integration/actions/doc/test_welcome_interactive_noee.py
  tests/integration/actions/images/base.py
  tests/integration/actions/images/test_direct_interactive_ee.py
  tests/integration/actions/images/test_direct_interactive_noee.py
  tests/integration/actions/images/test_welcome_interactive_ee.py
  tests/integration/actions/images/test_welcome_interactive_noee.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/inventory/test_direct_interactive_ee.py
  tests/integration/actions/inventory/test_direct_interactive_noee.py
  tests/integration/actions/inventory/test_stdout_tmux.py
  tests/integration/actions/inventory/test_welcome_interactive_ee.py
  tests/integration/actions/inventory/test_welcome_interactive_noee.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/replay/test_direct_interactive_ee.py
  tests/integration/actions/replay/test_direct_interactive_noee.py
  tests/integration/actions/replay/test_welcome_interactive_ee.py
  tests/integration/actions/replay/test_welcome_interactive_noee.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run/test_direct_interactive_ee.py
  tests/integration/actions/run/test_direct_interactive_noee.py
  tests/integration/actions/run/test_stdout_tmux.py
  tests/integration/actions/run/test_welcome_interactive_ee.py
  tests/integration/actions/run/test_welcome_interactive_noee.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/stdout/test_direct_interactive_ee.py
  tests/integration/actions/stdout/test_direct_interactive_noee.py
  tests/integration/actions/stdout/test_welcome_interactive_ee.py
  tests/integration/actions/stdout/test_welcome_interactive_noee.py
  tests/integration/actions/templar/base.py
  tests/integration/actions/templar/test_direct_interactive_ee.py
  tests/integration/actions/templar/test_direct_interactive_noee.py
  tests/integration/actions/templar/test_welcome_interactive_ee.py
  tests/integration/actions/templar/test_welcome_interactive_noee.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
Labels: gate, skip-changelog, bot:chronographer:skip

#641 [typing] Ensure `:run` passes rounded int to `utils.human_time`
  docs/changelog-fragments.d/640.misc.md
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/utils.py
  tests/unit/test_utils.py
Labels: gate, bot:chronographer:provided

#674 [lint] Add tests directory to pylint
  tox.ini
Labels: gate, tests, bot:chronographer:skip

#667 Fix the externally managed file by partialy reverting invalid "Fix linting regressions (#665)"
  docs/_ext/spelling_stub_ext.py
Labels: gate, tests, bot:chronographer:skip

#675 zuul: remove dependency on ansible-runner
  .zuul.d/jobs.yaml
  .zuul.d/project.yaml
  playbooks/pre-run.yaml
Labels: gate, bot:chronographer:skip

#681 Use a 2-line base indentation style @ tox sections
  tox.ini
Labels: gate, bot:chronographer:skip

#680 Add initial CoC/contributing/security docs infrastructure
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .pre-commit-config.yaml
  docs/changelog-fragments.d/680.internal.1.md
  docs/changelog-fragments.d/680.internal.2.md
  docs/changelog-fragments.d/680.internal.3.md
  docs/conf.py
  docs/contributing/code_of_conduct.md
  docs/contributing/guidelines.md
  docs/contributing/security.md
  docs/index.md
Labels: documentation, gate, bot:chronographer:provided

#664 Move global flake8 ignores to per-file
  docs/changelog-fragments.d/662.internal.md
  docs/changelog-fragments.d/664.internal.md
  tox.ini
Labels: gate, tests, skip-changelog, bot:chronographer:provided

#682 Rename license files to txt
  licenses/LICENSE.asottile_tm_tokenize.all.txt
  licenses/LICENSE.dark_vs.json.txt
  licenses/LICENSE.source.json.json.txt
  licenses/LICENSE.source.yaml.json.txt
  licenses/LICENSE.text.html.basic.json.txt
  licenses/LICENSE.text.html.derivative.json.txt
  licenses/LICENSE.text.html.markdown.json.txt
  licenses/LICENSE.text.log.json.txt
Labels: gate, skip-changelog, bot:chronographer:skip

#679 Fixed trailing whitespace
  .pre-commit-config.yaml
  docs/faq.md
  licenses/LICENSE.source.json.json.txt
  tests/fixtures/integration/execution_environment/ansible-navigator_disable_ee.yml
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/smoketests/scenarios/smoke-config.yml
  tox.ini
Labels: gate, bot:chronographer:skip

#687 Bump pre-commit hooks
  .pre-commit-config.yaml
Labels: gate, bot:chronographer:skip

#690 Avoid spelling fixture dumps
  .pre-commit-config.yaml
Labels: gate, bot:chronographer:skip

#691 Add lint-vetting job for all optional linters
  .pre-commit-config.yaml
  .zuul.d/jobs.yaml
  .zuul.d/project.yaml
  tox.ini
Labels: gate, bot:chronographer:skip

#692 [docs] Small contributors guide update
  .github/CONTRIBUTING.md
Labels: gate, bot:chronographer:skip, impatience-allowed

#678 Ensure flake8 and yamllint run from pre-commit
  bindep.txt
  test-requirements.txt
  tox.ini
Labels: gate, bot:chronographer:skip

#685 Fix end-of-file
  .pre-commit-config.yaml
  docs/param_details.yml
  licenses/LICENSE.dark_vs.json.txt
  licenses/LICENSE.source.json.json.txt
  licenses/LICENSE.source.yaml.json.txt
  licenses/LICENSE.text.html.basic.json.txt
  licenses/LICENSE.text.html.derivative.json.txt
  licenses/LICENSE.text.html.markdown.json.txt
  licenses/LICENSE.text.log.json.txt
  pyproject.toml
  requirements.txt
  share/ansible_navigator/grammar/JSON.tmLanguage.json
  share/ansible_navigator/grammar/html-derivative.tmLanguage.json
  share/ansible_navigator/grammar/html.tmLanguage.json
  share/ansible_navigator/grammar/log.tmLanguage.json
  share/ansible_navigator/grammar/markdown.tmLanguage.json
  share/ansible_navigator/grammar/yaml.tmLanguage.json
  share/ansible_navigator/themes/terminal_colors.json
  src/ansible_navigator/actions/write_file.py
  tests/fixtures/ansible.cfg
  tests/fixtures/integration/actions/doc/test_direct_interactive_ee.py/test/module_doc_fail/0.json
  tests/fixtures/integration/actions/doc/test_direct_interactive_noee.py/test/module_doc_fail/0.json
  tests/fixtures/integration/actions/doc/test_welcome_interactive_ee.py/test/module_doc_fail/1.json
  tests/fixtures/integration/actions/doc/test_welcome_interactive_noee.py/test/module_doc_fail/1.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/inventory/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/replay/playbook-artifact.json
  tests/fixtures/integration/actions/run/inventory
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/pass_environment_variable/ansible-navigator.yml
  tests/fixtures/integration/set_environment_variable/ansible-navigator.yml
  tests/fixtures/integration/stdout_exit_codes/site.yml
  tests/smoketests/scenarios/smoke-config.yml
Labels: gate, bot:chronographer:skip

#683 Move the flake8 config into a standalone location
  .flake8
  docs/changelog-fragments.d/683.internal.md
  tox.ini
Labels: gate, tests, structural, bot:chronographer:provided

#686 Ensure mypy runs via pre-commit
  .gitignore
  .zuul.d/jobs.yaml
  test-requirements.txt
  tox.ini
Labels: gate, bot:chronographer:skip

#676 zuul: enable testing with full py36-py310 range
  .zuul.d/jobs.yaml
  .zuul.d/project.yaml
Labels: gate, bot:chronographer:skip

#660 Add a config for darglint
  .darglint
Labels: gate, tests, skip-changelog, bot:chronographer:skip

#695 [docs] Clarify the current state of `black`
  .github/CONTRIBUTING.md
Labels: gate, bot:chronographer:skip

#707 Fixed various spelling errors
  docs/_ext/single_sourced_data.py
  share/ansible_navigator/utils/catalog_collections.py
  share/ansible_navigator/utils/image_introspect.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form_defs.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/sentinals.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/utils.py
  tests/conftest.py
  tests/integration/_action_run_test.py
  tests/integration/_tmux_session.py
  tests/unit/configuration_subsystem/test_configurator.py
  tests/unit/configuration_subsystem/test_mode_subcommand_action.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/test_utils.py
Labels: gate, bot:chronographer:skip

#710 Rename module name sentinals to sentinels (misspell)
  .flake8
  .pre-commit-config.yaml
  docs/changelog-fragments.d/710.internal.md
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/sentinels.py
  src/ansible_navigator/ui_framework/validators.py
Labels: gate, bot:chronographer:provided

#718 More spellchecking fixes
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  tests/unit/test_utils.py
Labels: gate, bot:chronographer:skip

#706 Sync annotated flake8 config with other projects
  .flake8
Labels: gate, bot:chronographer:skip

#705 [tests] grep case insensitive UPDATE_FIXTURES
  tox.ini
Labels: gate, tests, bot:chronographer:skip

#696 [tests] Preset condition var
  tests/integration/actions/collections/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
Labels: gate, tests, bot:chronographer:skip

#725 Address PT007 linting rule
  tests/integration/test_stdout_exit_codes.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/runner/test_api.py
  tests/unit/test_cli.py
  tests/unit/test_utils.py
Labels: gate, tests, bot:chronographer:skip

#724 Address E800 flake8 linting rule
  .flake8
  docs/conf.py
  src/ansible_navigator/actions/refresh.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/tm_tokenize/grammars.py
  src/ansible_navigator/tm_tokenize/reg.py
  tests/fixtures/common/collections/ansible_collections/testorg/coll_1/plugins/modules/mod_1.py
Labels: gate, tests, bot:chronographer:skip

#728 More spellcheck fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .pre-commit-config.yaml
Labels: gate, bot:chronographer:skip

#708 Use tox lint job and document it
  .github/CONTRIBUTING.md
  .markdownlint.yaml
  .zuul.d/jobs.yaml
  docs/changelog-fragments.d/708.internal.md
  tox.ini
Labels: gate, bug, bot:chronographer:provided

#732 Fix spelling errors in `src`
  src/ansible_navigator/__main__.py
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/app.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/runner/__init__.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command_base.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/tm_tokenize/rules.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_defs.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/ui_config.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/utils.py
Labels: gate, bot:chronographer:skip

#731 Fix and enable tests with py36 and py37
  .zuul.d/jobs.yaml
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/9.json
  tests/integration/actions/config/base.py
  tests/integration/actions/config/test_direct_interactive_noee.py
  tests/integration/actions/config/test_welcome_interactive_noee.py
Labels: gate, tests, bot:chronographer:skip

#736 Bump flake8 WPS plugin to v0.16.0
  .pre-commit-config.yaml
  docs/changelog-fragments.d/736.internal.md
Labels: gate, tests, bot:chronographer:provided

#727 Make codespell an official linter
  .github/CONTRIBUTING.md
  .pre-commit-config.yaml
  docs/changelog-fragments.d/727.internal.md
Labels: gate, bot:chronographer:provided, quorum-required

#740 [lint-vetting] Allow implicit string concatenation
  .flake8
Labels: gate, bot:chronographer:skip

#735 [typing] Add `ApplicationConfiguration` to `__init__` in actions
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/filter.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/quit.py
  src/ansible_navigator/actions/refresh.py
  src/ansible_navigator/actions/rerun.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/sample_working.py
  src/ansible_navigator/actions/save.py
  src/ansible_navigator/actions/select.py
  src/ansible_navigator/actions/serialize_json.py
  src/ansible_navigator/actions/serialize_yaml.py
  src/ansible_navigator/actions/stdout.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/actions/write_file.py
Labels: gate, bot:chronographer:skip

#739 Restore execution of pre-commit from inside tox -e lint
  tox.ini
Labels: gate, bot:chronographer:skip

#624 `exec` subcommand
  docs/changelog-fragments.d/526.feature.md
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/app.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/fixtures/integration/actions/exec/ansible-navigator.yaml
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/1.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/2.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/3.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/1.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/actions/exec/__init__.py
  tests/integration/actions/exec/base.py
  tests/integration/actions/exec/test_stdout_config_cli.py
  tests/integration/actions/exec/test_stdout_config_file.py
  tests/unit/actions/test_exec.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/configuration_subsystem/test_precedence.py
Labels: gate, bot:chronographer:provided

#744 [lint] Fix/disable pylint errors
  share/ansible_navigator/utils/catalog_collections.py
  share/ansible_navigator/utils/image_introspect.py
Labels: gate, bot:chronographer:skip

#743 pylint: address unspecified-encoding rule
  docs/_ext/single_sourced_data.py
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  tests/integration/actions/exec/base.py
Labels: bot:chronographer:skip

#748 [lint] Fix lint issues in tests/unit/runner
  tests/unit/runner/__init__.py
  tests/unit/runner/test_api.py
Labels: gate, bot:chronographer:skip

#749 [lint] Fix lint errors in `docs` directory
  docs/_ext/single_sourced_data.py
  docs/conf.py
Labels: gate, bot:chronographer:skip

#746 [lint] Fix several lint errors
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/utils.py
Labels: gate, bot:chronographer:skip

#745 [lint] Add encoding in share directory for file open
  share/ansible_navigator/utils/catalog_collections.py
Labels: gate, bot:chronographer:skip

#750 Add py36/py37 to zuul gate
  .zuul.d/project.yaml
Labels: gate, bot:chronographer:skip

#751 [lint] Unused var and import error
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/actions/config.py
Labels: gate, bot:chronographer:skip

#754 [lint] Fix pylint `no-member` and `not-an-iterable`
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_utils.py
Labels: gate, bot:chronographer:skip

#756 [lint] Unpin the pylint version
  test-requirements.txt
  tox.ini
Labels: gate, bot:chronographer:skip

#741 [lint-vetting] Allow `hasattr` and others
  .flake8
Labels: gate, bot:chronographer:skip

#760 tox: move lint-vetting section
  tox.ini
Labels: gate, bot:chronographer:skip

#737 Shorten output examples in CONTRIBUTING doc
  .github/CONTRIBUTING.md
  .markdownlint.yaml
Labels: documentation, gate, bot:chronographer:skip

#762 Mention the end of linting output in contributing
  .github/CONTRIBUTING.md
Labels: gate, bot:chronographer:skip

#759 Unify calling pylint from different toxenvs
  .pre-commit-config.yaml
  .pylintrc
  test-requirements.txt
  tox.ini
Labels: gate, tests, bot:chronographer:skip

#738 [configuration] delayed postprocs, extra volmounts
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/configuration_subsystem/test_navigator_post_processor.py
Labels: gate, bot:chronographer:skip

#766 Add differing aliases to flake8 hooks @ pre-commit
  .pre-commit-config.yaml
Labels: gate, tests, new, bot:chronographer:skip
