Repository ansible/ansible-navigator, pull requests merged in 2021-11, with the labels that each got.

#597 Update __task when runner event is in `ok`, `skipped`, `unreachable` and `failed` state
  src/ansible_navigator/actions/run.py
  tests/fixtures/integration/actions/run/site.yaml
  tests/fixtures/integration/actions/run/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee.py/test/12.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee.py/test/13.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/12.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/13.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_ee.py/test/13.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_ee.py/test/14.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/13.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/14.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/run/vars/external_vars.yaml
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/8.json
  tests/integration/actions/run/test_stdout_tmux.py
Labels: gate

#612 Update `:config` fixtures for ansible-core 2.12
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/7.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/8.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_param_use.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_param_use.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/3.json
  tests/integration/actions/config/base.py
Labels: gate

#593 Detailed installation instructions for linux/macos/windows
  README.md
  docs/conf.py
  docs/index.md
  docs/installation.md
  docs/requirements.in
Labels: gate

#614 Replace use of yum w/ rpm
  share/ansible_navigator/utils/image_introspect.py
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/11.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/12.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/13.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/12.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/13.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/11.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/12.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/13.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/14.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/12.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/13.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/14.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/9.json
Labels: gate

#622 Make use of detached links in the docs
  README.md
  docs/installation.md
Labels: gate

#621 `:images` fix for `Name` in `Description`
  share/ansible_navigator/utils/image_introspect.py
  tests/unit/test_image_introspection.py
Labels: gate

#623 Initial cleanup of runner directory
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/runner/__init__.py
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/api.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/runner/command_base.py
  tests/integration/_cli2runner.py
  tests/unit/actions/test_run.py
  tests/unit/runner/test_api.py
Labels: skip-changelog

#627 set task duration to zero if None (fixes #598)
  src/ansible_navigator/actions/run.py
Labels: gate, bug

#630 Followup on PR comments in #623
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/runner/__init__.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/runner/command_base.py
Labels: gate
