Repository ansible/ansible-navigator, pull requests merged in 2022-04, with the labels that each got.

#1172 more ui_framework/form_* docstring updates (D/DAR)
  .flake8
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_defs.py
  src/ansible_navigator/ui_framework/form_handler_button.py
Labels: bot:chronographer:skip

#1178 Add plugin path information in collection stdout
  docs/changelog-fragments.d/1178.bugfix.md
  src/ansible_navigator/actions/collections.py
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/1.json
Labels: bug, bot:chronographer:provided

#1174 Fix lint errors, add some types in lint tests (D/DAR)
  tests/integration/actions/lint/__init__.py
  tests/integration/actions/lint/base.py
  tests/integration/actions/lint/test_direct_interactive_ee.py
  tests/integration/actions/lint/test_direct_interactive_no_errors_ee.py
  tests/integration/actions/lint/test_welcome_interactive_ee.py
Labels: documentation, bug, bot:chronographer:skip

#1173 Clean-up settings messages via stderr and TUI
  share/ansible_navigator/themes/terminal_colors.json
  src/ansible_navigator/action_base.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/utils.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/field_curses_information.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/utils/ansi.py
  src/ansible_navigator/utils/definitions.py
  src/ansible_navigator/utils/functions.py
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/17.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/18.json
  tests/fixtures/integration/actions/exec/test_stdout_cli.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_cli.py/test/1.json
  tests/integration/actions/collections/base.py
  tests/integration/actions/exec/test_stdout_cli.py
  tests/integration/settings_from_cli/test_json_schema_errors.py
  tests/unit/configuration_subsystem/post_processors/test_time_zone.py
  tests/unit/configuration_subsystem/test_ansible_config_parse.py
  tests/unit/configuration_subsystem/test_broken_settings.py
  tests/unit/configuration_subsystem/test_invalid_params.py
Labels: bot:chronographer:skip

#1180 Italic fix on macOS
  src/ansible_navigator/ui_framework/ui_constants.py
Labels: bot:chronographer:skip

#1183 Unneccessary initialization of variable
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
Labels: bot:chronographer:skip

#1177 Improve help output
  docs/conf.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/parser.py
  tests/smoke/no_test_dependencies.py
Labels: enhancement, bot:chronographer:skip

#1184 Add schema defaults
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/transform.py
Labels: bot:chronographer:skip

#1187 Add `version_added` to all subcommands and settings entries
  docs/_ext/single_sourced_data.py
  docs/param_details.yml
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/unit/actions/settings/test_settings.py
  tests/unit/configuration_subsystem/test_mode_subcommand_action.py
  tests/unit/configuration_subsystem/test_presentable.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
Labels: bot:chronographer:skip

#1188 Make test dependencies an extra
  .github/CONTRIBUTING.md
  setup.cfg
  test-requirements.txt
  tox.ini
Labels: bot:chronographer:skip

#1189 Make requirements.txt a lock file
  .github/dependabot.yml
  cspell.config.yaml
  requirements.txt
  tox.ini
Labels: bot:chronographer:skip

#1191 Move docs deps into an extra
  .github/workflows/tox.yml
  .readthedocs.yml
  docs/contributing/guidelines.md
  docs/requirements.in
  requirements.txt
  setup.cfg
  tox.ini
Labels: bot:chronographer:skip

#1182 Settings file migration
  .prettierignore
  docs/changelog-fragments.d/1182.feature.md
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/utils/ansi.py
  src/ansible_navigator/utils/definitions.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/version_migration/__init__.py
  src/ansible_navigator/utils/version_migration/definitions.py
  src/ansible_navigator/utils/version_migration/migrate.py
  src/ansible_navigator/utils/version_migration/settings_file.py
  src/ansible_navigator/utils/version_migration/v1_v2_settings_file.py
  tests/conftest.py
  tests/fixtures/integration/version_migration/ansible-navigator.v1
  tests/fixtures/integration/version_migration/ansible-navigator_1.1.json
  tests/fixtures/integration/version_migration/ansible-navigator_1.1.yaml
  tests/fixtures/integration/version_migration/ansible-navigator_1.1_corrected.json
  tests/fixtures/integration/version_migration/ansible-navigator_1.1_corrected.yaml
  tests/fixtures/integration/version_migration/ansible-navigator_all.yml
  tests/fixtures/integration/version_migration/ansible-navigator_all_corrected.yml
  tests/fixtures/integration/version_migration/ansible-navigator_some.yml
  tests/fixtures/integration/version_migration/ansible-navigator_some_corrected.yml
  tests/integration/_tmux_session.py
  tests/integration/version_migration/__init__.py
  tests/integration/version_migration/test_v1_v2_settings.py
  tests/unit/utils/test_dot_paths.py
Labels: bot:chronographer:skip

#1192 Optimize GHA execution
  .github/workflows/tox.yml
Labels: bot:chronographer:skip

#1193 Minor tox.ini fixes
  tox.ini
Labels: bot:chronographer:skip

#1195 Migration fixes
  src/ansible_navigator/utils/ansi.py
  src/ansible_navigator/utils/version_migration/definitions.py
  src/ansible_navigator/utils/version_migration/migrate.py
  src/ansible_navigator/utils/version_migration/settings_file.py
  src/ansible_navigator/utils/version_migration/v1_v2_settings_file.py
  tests/integration/version_migration/test_v1_v2_settings.py
Labels: bot:chronographer:skip

#1196 Typo fix (willforce)
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
Labels: bot:chronographer:skip

#1197 Fix tox entry for lint-candidates
  tox.ini
Labels: bug, bot:chronographer:skip

#1181 Add generated configuration schema file
  .config/dictionary.txt
  .prettierignore
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/data/__init__.py
  src/ansible_navigator/data/ansible-navigator.json
  tox.ini
Labels: bot:chronographer:skip

#1200 Remove max size none for lru_cache
  src/ansible_navigator/ui_framework/colorize.py
Labels: bot:chronographer:skip

#1201 Remove flake8-quotes
  .flake8
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
Labels: bot:chronographer:skip, skip-changelog

#1202 Update run action to address templated task name for tasks in playbook
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/utils/functions.py
Labels: bot:chronographer:skip

#1212 Docstring fixes for src/ansible_navigator/utils/functions.py
  .flake8
  src/ansible_navigator/utils/functions.py
Labels: documentation, bot:chronographer:skip

#1214 doc string additions for ui_framework/form* (D/DAR)
  .flake8
  src/ansible_navigator/data/__init__.py
  src/ansible_navigator/ui_framework/form_handler_information.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/form_handler_working.py
  src/ansible_navigator/ui_framework/form_utils.py
Labels: documentation, bot:chronographer:skip
