Repository ansible/ansible-navigator, pull requests merged in 2022-08, with the labels that each got.

#1264 fix lint sub command version_added
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
Labels: bug, bot:chronographer:skip

#1267 Fixing additional test docstrings (D/DAR)
  .flake8
  tests/unit/actions/collections/test_collection_doc_cache_path.py
  tests/unit/actions/test_config.py
  tests/unit/actions/test_inventory.py
  tests/unit/image_manager/test_image_puller.py
  tests/unit/test_cli.py
  tests/unit/test_image_introspection.py
  tests/unit/ui_framework/test_colorize.py
  tests/unit/utils/test_functions.py
Labels: documentation, bug, bot:chronographer:skip

#1268 More additional test docstrings (D/DAR)
  .flake8
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/configuration_subsystem/test_broken_settings.py
  tests/unit/configuration_subsystem/test_configurator.py
  tests/unit/configuration_subsystem/test_container_engine_auto.py
Labels: bug, bot:chronographer:skip

#1271 Repair docs build
  docs/conf.py
Labels: skip-changelog

#1270 Implement PEP-563
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/content_defs.py
  src/ansible_navigator/tm_tokenize/compiler.py
  src/ansible_navigator/tm_tokenize/reg.py
  src/ansible_navigator/tm_tokenize/rules.py
  src/ansible_navigator/tm_tokenize/state.py
  src/ansible_navigator/tm_tokenize/tokenize.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_radio.py
  tests/integration/_cli2runner.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
Labels: skip-changelog

#1272 Ensure docs build with py311
  docs/conf.py
Labels: skip-changelog

#1280 Implement annotation workaround for sphinx
  docs/conf.py
  src/ansible_navigator/app_public.py
  src/ansible_navigator/ui_framework/ui.py
  tox.ini
Labels: bot:chronographer:skip, skip-changelog
