Repository ansible/ansible-navigator, pull requests merged in 2022-07, with the labels that each got.

#1247 Exempt macOS from a `/dev/queue` check when `podman` is the container engine
  docs/changelog-fragments.d/1247.bugfix.md
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
Labels: bug, bot:chronographer:provided

#1250 Remove lxml test dependency
  requirements.txt
  setup.cfg
Labels: bug, bot:chronographer:skip

#1251 Default factory for ApplicationConfiguration
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/utils.py
Labels: bug, bot:chronographer:skip

#1255 Require well formatted docstrings
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#1254 Update runner warning exclusion
  tests/unit/test_circular_imports.py
Labels: bot:chronographer:skip

#1256 Require later setuptools for python 3.11
  setup.cfg
Labels: bot:chronographer:skip

#1257 Fix pre-commit hook version
  .pre-commit-config.yaml
Labels: bot:chronographer:skip, skip-changelog

#1246 Add support for py3.11
  .config/dictionary.txt
  .github/workflows/release.yml
  .github/workflows/tox.yml
  bindep.txt
  docs/changelog-fragments.d/1246.feature.md
  setup.cfg
  tox.ini
Labels: bot:chronographer:provided, skip-changelog

#1260 Disable link-image-reference-definitions
  .pre-commit-config.yaml
  CHANGELOG.md
Labels: bot:chronographer:skip, impatience-allowed
