Repository ansible/ansible-navigator, pull requests merged in 2022-01, with the labels that each got.

#775 Cap the version `Sphinx` below 4.4.0
  docs/requirements.in
Labels: gate, skip-changelog, bot:chronographer:skip

#779 Test for circular imports in project
  tests/unit/test_circular_imports.py
Labels: gate, tests, bot:chronographer:skip

#783 Correct parameters in docstrings so they match function signatures
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/filter.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/quit.py
  src/ansible_navigator/actions/refresh.py
  src/ansible_navigator/actions/rerun.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/sample_working.py
  src/ansible_navigator/actions/save.py
  src/ansible_navigator/actions/select.py
  src/ansible_navigator/actions/serialize_json.py
  src/ansible_navigator/actions/serialize_yaml.py
  src/ansible_navigator/actions/stdout.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/utils.py
  tests/unit/configuration_subsystem/test_navigator_post_processor.py
  tests/unit/runner/__init__.py
  tests/unit/test_circular_imports.py
  tests/unit/test_utils.py
Labels: gate, bot:chronographer:skip

#770 Store the settings file path for use later in the `:settings` action
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/initialization.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_internals.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
Labels: gate, bot:chronographer:skip

#789 Remove unnecessary generator inside inventory max modified times fuction
  src/ansible_navigator/actions/inventory.py
Labels: gate, bot:chronographer:skip

#791 Small formatting change for comment in setup.py
  setup.py
Labels: gate, bot:chronographer:skip

#787 Changes making the use of double quotes consistent throughout
  .flake8
  docs/_ext/spelling_stub_ext.py
  docs/conf.py
Labels: gate, bot:chronographer:skip

#793 Switch from short var names to longer in one test file
  tests/unit/test_circular_imports.py
Labels: gate, bot:chronographer:skip

#795 Enable automatic import statement sorting
  .github/CONTRIBUTING.md
  .pre-commit-config.yaml
Labels: gate, bot:chronographer:skip, quorum-required

#800 Changes necessary to have the `pylint` configuration in only one location
  .pylintrc
  pyproject.toml
Labels: gate, bot:chronographer:skip

#792 Disable warnings related to the use of assert in the tests directory as reported with `lint-vetting`
  .flake8
Labels: gate, bot:chronographer:skip

#801 Properly format `pylint` disable in `pyproject.yaml`
  pyproject.toml
Labels: gate, bot:chronographer:skip

#650 Add MVP GHA workflows
  .github/workflows/tox.yml
  tests/integration/actions/config/test_welcome_interactive_param_use.py
  tests/integration/actions/config/test_welcome_interactive_specified_config.py
Labels: gate, skip-changelog, bot:chronographer:skip

#790 Form button validation, pass a `List` not `Generator`
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/validators.py
Labels: gate, bot:chronographer:skip

#796 Move `WPSXXX` errors reported by `lint-vetting` into `per-file-ignores`
  .flake8
Labels: gate, bot:chronographer:skip

#803 Predefine `FieldValidatorState` and `FieldValidatorStates`
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/form_defs.py
  src/ansible_navigator/ui_framework/validators.py
Labels: gate, bot:chronographer:skip

#782 Activate `pylint-pytest` plugin
  pyproject.toml
Labels: gate, tests, bot:chronographer:skip

#805 Disable 2 `flake8-bandit` checks (S404 and S603) in one unit test
  tests/unit/test_circular_imports.py
Labels: gate, bot:chronographer:skip

#806 Rename `shell` to `use_shell` in one unit test
  tests/unit/actions/test_exec.py
Labels: gate, bot:chronographer:skip

#807 Add `mod` as permitted RST role
  .flake8
Labels: gate, bot:chronographer:skip

#726 Check against both Python 3.10 and 3.6 in MyPy
  .pre-commit-config.yaml
  docs/changelog-fragments.d/726.internal.md
  tox.ini
Labels: gate, tests, good first issue, bot:chronographer:provided

#810 Update `__init__` `:run` action (doc string and params)
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:skip

#797 Enable `useless-suppression` and remove errors that had been uselessly suppressed for `pylint`
  pyproject.toml
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/replay.py
  src/ansible_navigator/actions/rerun.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/sample_working.py
  src/ansible_navigator/actions/select.py
  src/ansible_navigator/actions/stdout.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/app.py
  src/ansible_navigator/app_public.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/runner/command_base.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_defs.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_option.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/validators.py
  src/ansible_navigator/utils.py
  tests/integration/_interactions.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/stdout/base.py
  tests/unit/configuration_subsystem/test_broken_settings.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/test_cli.py
Labels: bot:chronographer:skip

#813 Fix the GHA `check` job to treat skips as failures
  .github/workflows/tox.yml
Labels: enhancement, tests, new, bot:chronographer:skip

#814 test: reduce verbosity for container pulling
  tox.ini
Labels: bot:chronographer:skip

#816 Add doc string to `__init__` in 7 files
  share/ansible_navigator/utils/catalog_collections.py
  share/ansible_navigator/utils/key_value_store.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/tm_tokenize/grammars.py
  tests/integration/_action_run_test.py
Labels: bot:chronographer:skip

#815 Add doc strings to `__init__` in the UI subsystem
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/form_handler_button.py
  src/ansible_navigator/ui_framework/form_handler_information.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/form_handler_working.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/menu_builder.py
Labels: bot:chronographer:skip

#821 Add doc strings to the `__init__` function for classes
  share/ansible_navigator/utils/image_introspect.py
  src/.pylint-spelling-private-dict
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/tm_tokenize/compiler.py
  src/ansible_navigator/tm_tokenize/fchainmap.py
  tests/integration/_tmux_session.py
Labels: bot:chronographer:skip

#819 Remove link in `actions/run.py` to Interaction
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:skip

#823 [tests] Changes to frequently failing templar integration tests
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/11.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/8.json
  tests/integration/actions/templar/base.py
Labels: bot:chronographer:skip

#825 Introduce an intermediate lint-candidates target
  .github/CONTRIBUTING.md
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  tox.ini
Labels: enhancement, tests, bot:chronographer:skip

#817 Add more vars to tox passenv
  tox.ini
Labels: bot:chronographer:skip

#799 Configure pylint to run as native pre-commit hook
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#828 Remove all exceptions for D107 from `.flake8`
  .flake8
Labels: bot:chronographer:skip

#822 Remove `type` and `rtype` in ``actions/run.py`` prepare_to_quit
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:skip

#826 Copy the tmux screen contents before modifiying
  tests/integration/actions/templar/base.py
Labels: tests, bot:chronographer:skip

#767 Add codecov integration
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog, bot:chronographer:skip

#831 Pass posargs to pytest on unit testing
  tox.ini
Labels: bot:chronographer:skip

#836 Documentation improvements in `docs/_ext/single_sourced_data.py` (D/DAR)
  .flake8
  docs/_ext/single_sourced_data.py
Labels: documentation, bot:chronographer:skip

#835 Updated pre-commit SKIP environment variable to reflect unenforced hooks
  tox.ini
Labels: bot:chronographer:skip

#808 Pin python version used by pre-commit
  .pre-commit-config.yaml
Labels: skip-changelog, bot:chronographer:skip

#818 Add `__all__` to subsystem `__init__` files
  src/ansible_navigator/command_runner/__init__.py
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/image_manager/__init__.py
  src/ansible_navigator/runner/__init__.py
  src/ansible_navigator/ui_framework/__init__.py
Labels: bot:chronographer:skip

#830 Remove unexplained `unused-import` `F401` from `.flake8`
  .flake8
Labels: bot:chronographer:skip

#833 Move most coverage options to pyproject.toml
  pyproject.toml
  tox.ini
Labels: bot:chronographer:skip

#841 Pre-commit and GHA python version to 3.10
  .github/workflows/tox.yml
  .pre-commit-config.yaml
Labels: tests, bot:chronographer:skip

#844 chore: fix concurrency condition for pushes
  .github/workflows/tox.yml
Labels: bot:chronographer:skip

#837 Documentation improvements in several files (D/DAR)
  .flake8
  docs/_ext/spelling_stub_ext.py
  setup.py
  share/ansible_navigator/utils/__init__.py
  share/ansible_navigator/utils/catalog_collections.py
Labels: documentation, bot:chronographer:skip

#842 Note python version requirement for tox in contributors guide
  .github/CONTRIBUTING.md
Labels: documentation, bot:chronographer:skip

#845 Move `flake8-quotes` entry to bottom of file and add explanation
  .flake8
Labels: bot:chronographer:skip

#846 Move `f`-string check from per-file to global
  .flake8
Labels: bot:chronographer:skip
