Repository ansible/ansible-navigator, pull requests merged in 2022-10, with the labels that each got.

#1297 Ignore case of error
  tests/integration/test_stdout_exit_codes.py
Labels: bot:chronographer:skip, impatience-allowed, skip-changelog

#1298 Prep for libtmux version 0.15 +
  tests/integration/_tmux_session.py
Labels: bot:chronographer:skip, skip-changelog

#1300 Fixture updates (no software changes)
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/7.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/16.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/16.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/11.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/25.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/25.json
  tests/fixtures/integration/actions/exec/test_stdout_file.py/test/2.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_no_errors_ee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/lint/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
Labels: bot:chronographer:skip, skip-changelog

#1305 Enable black formatting
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#1296 Update imports for ApplicationConfiguration
  src/ansible_navigator/action_base.py
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/actions/__init__.py
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/filter.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/quit.py
  src/ansible_navigator/actions/refresh.py
  src/ansible_navigator/actions/rerun.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/sample_working.py
  src/ansible_navigator/actions/save.py
  src/ansible_navigator/actions/select.py
  src/ansible_navigator/actions/serialize_json.py
  src/ansible_navigator/actions/serialize_yaml.py
  src/ansible_navigator/actions/stdout.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/app_public.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/logger.py
  tests/unit/configuration_subsystem/test_presentable.py
Labels: bot:chronographer:skip

#1306 Better puller logging
  src/ansible_navigator/image_manager/puller.py
Labels: bot:chronographer:skip, skip-changelog

#1307 Update CHANGELOG.md
  CHANGELOG.md
Labels: skip-changelog

#1312 Update version in schema
  src/ansible_navigator/data/ansible-navigator.json
Labels: skip-changelog

#1309 Remove unused playbooks directory
  playbooks/pre-run.yaml
Labels: skip-changelog

#1316 Diagnostics file permissions
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/utils/write_json.py
  tests/integration/diagnostics/test_for_permissions.py
Labels: bug, AAP

#1317 Add label check for EE
  src/ansible_navigator/actions/images.py
Labels: enhancement

#1319 Simplifies `VolumeMount` class and Resolve paths to accept `~` in volume mount
  src/ansible_navigator/configuration_subsystem/definitions.py
  tests/unit/configuration_subsystem/post_processors/test_execution_environment_volume_mounts.py
Labels: bug

#1322 Update macOS installation instructions
  docs/installation.md
Labels: bug
