Repository ansible/ansible-navigator, pull requests merged in 2022-02, with the labels that each got.

#763 Make black run under pre-commit
  .pre-commit-config.yaml
  test-requirements.txt
  tox.ini
Labels: bot:chronographer:skip

#850 Documentation improvements in `image_introspection.py` file (D/DAR)
  .flake8
  share/ansible_navigator/utils/image_introspect.py
Labels: documentation, bot:chronographer:skip

#851 Documentation improvements in `key_value_store.py` file (D/DAR)
  .flake8
  share/ansible_navigator/utils/key_value_store.py
Labels: documentation, bot:chronographer:skip

#852 [exec] *actually* set env vars from config
  src/ansible_navigator/actions/exec.py
  tests/fixtures/integration/actions/exec/ansible-navigator.yaml
  tests/integration/actions/exec/test_stdout_config_file.py
Labels: bot:chronographer:skip

#853 Reduce pylint run time
  .pre-commit-config.yaml
  pyproject.toml
Labels: bot:chronographer:skip

#854 Decrease probability of false-positive `templar` integration test failures
  tests/integration/actions/templar/base.py
Labels: bot:chronographer:skip

#856 Documentation improvements in `_` files (D/DAR)
  .flake8
Labels: bot:chronographer:skip

#863 [image puller] fix tag parsing for port numbers
  docs/changelog-fragments.d/863.bugfix.md
  src/ansible_navigator/image_manager/puller.py
  tests/unit/image_manager/test_image_puller.py
Labels: bot:chronographer:provided

#862 Reduce black verbosity
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#859 Documentation improvements in `action_runner.py` file (D/DAR)
  .flake8
  src/ansible_navigator/action_runner.py
Labels: documentation, bot:chronographer:skip

#865 [collections] append, not overwrite, EE volmounts
  docs/changelog-fragments.d/764.bugfix.md
  src/ansible_navigator/actions/collections.py
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/0.json
  tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py
Labels: bot:chronographer:provided

#867 Retry and warn for libtmux `server exited unexpectedly`
  tests/integration/_tmux_session.py
  tox.ini
Labels: tests, bot:chronographer:skip

#848 Add builder subcommand to manage EE builds
  docs/changelog-fragments.d/459.feature.md
  setup.cfg
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/fixtures/common/builder/test_ee/execution-environment.yml
  tests/fixtures/common/builder/test_ee/requirements.yml
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/7.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/actions/builder/__init__.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/builder/test_stdout_tmux.py
  tests/unit/configuration_subsystem/data.py
Labels: bot:chronographer:provided

#870 Documentation improvements in one `test_direct_interactive_ee_with_volmount.py` (D/DAR)
  tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py
Labels: documentation, bot:chronographer:skip

#869 Make a documentation help plea in pre-commit
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#857 Remove an accidentally added private spelling dict file
  src/.pylint-spelling-private-dict
Labels: bot:chronographer:skip

#861 Reduce `pre-commit` verbosity in `tox.ini`
  tox.ini
Labels: bot:chronographer:skip

#858 Stop ignoring `D412` rule in the flake8 and precommit configurations
  .flake8
  .pre-commit-config.yaml
Labels: documentation, bot:chronographer:skip

#872 Guard against using unittest ecosystem within pylint
  pyproject.toml
  tests/integration/_cli2runner.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
  tests/unit/actions/test_run.py
  tests/unit/configuration_subsystem/test_configurator.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/test_cli.py
  tests/unit/test_log_append.py
Labels: enhancement, tests, bot:chronographer:skip

#871 Reduce false fixture changes for `config` integration tests
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/7.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/8.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_param_use.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_param_use.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/3.json
  tests/integration/actions/config/base.py
  tests/integration/actions/config/test_welcome_interactive_param_use.py
  tests/integration/actions/config/test_welcome_interactive_specified_config.py
Labels: tests, bot:chronographer:skip

#860 Documentation improvements in `actions` package (D/DAR)
  .flake8
  src/ansible_navigator/actions/__init__.py
  src/ansible_navigator/actions/_actions.py
Labels: documentation, bot:chronographer:skip

#864 Disable anchors and aliases when serializing to yaml
  src/ansible_navigator/_yaml.py
  tests/unit/test_yaml.py
Labels: bot:chronographer:skip

#873 Remove duplicate pydocstyle check from precommit configuration
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#866 Error out when `/dev/mqueue/` doesn't exist and container engine is `podman` with EE support enabled
  docs/changelog-fragments.d/866.bugfix.md
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
Labels: bot:chronographer:provided

#877 Format the precommit file using RH vscode plugin defaults
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#878 Documentation improvements in four actions (D/DAR)
  .flake8
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
Labels: documentation, bot:chronographer:skip

#883 Correct spelling of indices throughout project
  src/ansible_navigator/ui_framework/ui.py
  tests/integration/_interactions.py
  tests/integration/actions/builder/test_stdout_tmux.py
  tests/integration/actions/config/test_direct_interactive_ee.py
  tests/integration/actions/config/test_direct_interactive_noee.py
  tests/integration/actions/config/test_stdout_tmux.py
  tests/integration/actions/config/test_welcome_interactive_ee.py
  tests/integration/actions/config/test_welcome_interactive_noee.py
  tests/integration/actions/config/test_welcome_interactive_param_use.py
  tests/integration/actions/config/test_welcome_interactive_specified_config.py
  tests/integration/actions/exec/test_stdout_config_cli.py
  tests/integration/actions/exec/test_stdout_config_file.py
  tests/integration/actions/images/test_direct_interactive_ee.py
  tests/integration/actions/images/test_direct_interactive_noee.py
  tests/integration/actions/images/test_welcome_interactive_ee.py
  tests/integration/actions/images/test_welcome_interactive_noee.py
  tests/integration/actions/inventory/test_direct_interactive_ee.py
  tests/integration/actions/inventory/test_direct_interactive_noee.py
  tests/integration/actions/inventory/test_stdout_tmux.py
  tests/integration/actions/inventory/test_welcome_interactive_ee.py
  tests/integration/actions/inventory/test_welcome_interactive_noee.py
  tests/integration/actions/run/test_direct_interactive_ee.py
  tests/integration/actions/run/test_direct_interactive_noee.py
  tests/integration/actions/run/test_stdout_tmux.py
  tests/integration/actions/run/test_welcome_interactive_ee.py
  tests/integration/actions/run/test_welcome_interactive_noee.py
  tests/integration/actions/templar/test_direct_interactive_ee.py
  tests/integration/actions/templar/test_direct_interactive_noee.py
  tests/integration/actions/templar/test_welcome_interactive_ee.py
  tests/integration/actions/templar/test_welcome_interactive_noee.py
Labels: bot:chronographer:skip

#887 Correct spelling of independent
  tests/integration/actions/collections/base.py
  tests/integration/conftest.py
Labels: bot:chronographer:skip

#886 Correct spelling of support
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/ui.py
Labels: bot:chronographer:skip

#884 Correct abbreviation of `environment variable` from `envvar` to `env_var` where possible
  docs/_ext/single_sourced_data.py
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/runner/base.py
  tests/integration/_interactions.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/test_utils.py
Labels: bot:chronographer:skip

#885 Correct the spelling of builder
  tests/integration/actions/builder/base.py
  tests/integration/actions/builder/test_stdout_tmux.py
Labels: bot:chronographer:skip

#888 Correct spelling of `collecion_cache` to `collection_cache`
  src/ansible_navigator/initialization.py
Labels: bot:chronographer:skip

#880 Docstring updates in 4 actions in `actions` package (D/DAR)
  .flake8
  src/ansible_navigator/actions/filter.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
Labels: documentation, bot:chronographer:skip

#881 Fix a few spelling mistakes that were encountered
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/ui_framework/ui.py
  tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py
  tests/integration/actions/exec/test_stdout_config_cli.py
  tests/unit/test_circular_imports.py
Labels: documentation, bot:chronographer:skip

#882 Remove trailing dot from a few parameter descriptions in docstrings
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/command_async.py
Labels: documentation, bot:chronographer:skip

#889 Spelling fixes across project
  docs/changelog-fragments.d/683.internal.md
  docs/changelog-fragments.d/README.md
  share/ansible_navigator/utils/image_introspect.py
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/tm_tokenize/LICENSE
  src/ansible_navigator/ui_framework/form_presenter.py
  tests/integration/_common.py
  tests/integration/_tmux_session.py
  tests/unit/actions/test_run.py
  tests/unit/configuration_subsystem/test_entries_sanity.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
  tests/unit/image_manager/test_image_puller.py
  tests/unit/runner/test_api.py
  tests/unit/test_cli.py
  tests/unit/test_yaml.py
  tests/unit/ui_framework/test_colorize.py
Labels: bot:chronographer:skip

#890 Revise `patch_curses` fixture
  tests/integration/conftest.py
Labels: tests, bot:chronographer:skip

#893 Remove abbreviations and non-words in `ui_framework/utils.py`
  src/ansible_navigator/ui_framework/utils.py
Labels: bot:chronographer:skip

#898 Remove some abbreviations in form presenter
  src/ansible_navigator/ui_framework/form_presenter.py
Labels: bot:chronographer:skip

#897 Remove some abbreviations in menu builder
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
Labels: bot:chronographer:skip

#892 Remove abbreviations for `command` and `classes` and process types in `image_introspection.py`
  share/ansible_navigator/utils/image_introspect.py
Labels: bot:chronographer:skip

#903 Replace ``cbox`` with ``check_box``
  src/ansible_navigator/ui_framework/field_option.py
Labels: bot:chronographer:skip

#900 Replace made-up words in utils
  src/ansible_navigator/utils.py
Labels: bot:chronographer:skip

#902 Unabbreviate chksum, fpath, cname in catalog_collections.py
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/actions/collections.py
Labels: bot:chronographer:skip

#895 Normalize `with open` context handler variable
  docs/_ext/single_sourced_data.py
  pyproject.toml
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  tests/integration/_common.py
  tests/integration/_tmux_session.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/exec/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
Labels: bot:chronographer:skip

#901 Normalize references to screen/viewport height and width
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
Labels: bot:chronographer:skip

#874 Replace `unittest` with `pytest` in cli tests and document endstate
  .flake8
  tests/integration/_cli2runner.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
Labels: tests, bot:chronographer:skip

#907 Improve some variable names in several actions
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:skip

#908 Remove dval and cval from test_config
  tests/unit/actions/test_config.py
Labels: bot:chronographer:skip

#911 Command runner and image inspector spelling and type fixes
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/image_manager/inspector.py
Labels: bot:chronographer:skip

#914 Remove zuul directory
  .zuul.d/jobs.yaml
  .zuul.d/project.yaml
Labels: bot:chronographer:skip

#912 Spelling and variable name improvements in several files
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/form_utils.py
  tests/integration/_common.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_stdout_exit_codes.py
  tests/unit/ui_framework/test_colorize.py
Labels: bot:chronographer:skip

#915 Remove root etc directory
  etc/.gitkeep
Labels: bot:chronographer:skip

#913 Remove smoke tests
  bindep.txt
  tests/smoketests/run.yml
  tests/smoketests/scenarios/00smoke.yml
  tests/smoketests/scenarios/roles/assert_substring/defaults/main.yml
  tests/smoketests/scenarios/roles/assert_substring/meta/main.yml
  tests/smoketests/scenarios/roles/assert_substring/tasks/main.yml
  tests/smoketests/scenarios/roles/send_keys/defaults/main.yml
  tests/smoketests/scenarios/roles/send_keys/meta/main.yml
  tests/smoketests/scenarios/roles/send_keys/tasks/main.yml
  tests/smoketests/scenarios/roles/tmux/destroy/meta/main.yml
  tests/smoketests/scenarios/roles/tmux/destroy/tasks/main.yml
  tests/smoketests/scenarios/roles/tmux/setup/meta/main.yml
  tests/smoketests/scenarios/roles/tmux/setup/tasks/main.yml
  tests/smoketests/scenarios/smoke-config.yml
  tests/smoketests/scenarios/test_user_config.yml
  tox.ini
Labels: bot:chronographer:skip

#905 Consolidate fixture retrieval in action integration tests
  tests/integration/_common.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/exec/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
Labels: bot:chronographer:skip

#917 Remove unused eventq from runner/CommandAsync
  src/ansible_navigator/runner/command_async.py
Labels: bot:chronographer:skip

#922 Improve variable names in ui.py
  src/ansible_navigator/ui_framework/ui.py
Labels: bot:chronographer:skip

#926 Remove rtype from docstrings
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils.py
Labels: bot:chronographer:skip

#924 Switch mqueue to message_queue
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
Labels: bot:chronographer:skip

#933 Update templar integration tests: look_fors, look_nots_ => present, absent
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/11.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/9.json
  tests/integration/actions/templar/base.py
  tests/integration/actions/templar/test_direct_interactive_ee.py
  tests/integration/actions/templar/test_direct_interactive_noee.py
  tests/integration/actions/templar/test_welcome_interactive_ee.py
  tests/integration/actions/templar/test_welcome_interactive_noee.py
Labels: tests, bot:chronographer:skip

#929 Update exec integration tests: look_fors, look_nots_ => present, absent
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/1.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/2.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/3.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/1.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/2.json
  tests/integration/actions/exec/base.py
  tests/integration/actions/exec/test_stdout_config_cli.py
  tests/integration/actions/exec/test_stdout_config_file.py
Labels: tests, bot:chronographer:skip

#928 Update builder integration tests: look_fors, look_nots_ => present, absent
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/7.json
  tests/integration/actions/builder/base.py
  tests/integration/actions/builder/test_stdout_tmux.py
Labels: tests, bot:chronographer:skip

#934 Remove unneeded code in tests
  tests/integration/_common.py
  tests/integration/_interactions.py
Labels: bot:chronographer:skip

#935 Per-file cspell exclusions
  docs/changelog-fragments.d/736.internal.md
  docs/conf.py
  docs/contributing/guidelines.md
  docs/faq.md
  docs/index.md
  docs/installation.md
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/ui.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/unit/configuration_subsystem/utils.py
  tests/unit/test_image_introspection.py
Labels: bot:chronographer:skip

#938 Allow 10 minutes for a builder build
  tests/integration/actions/builder/base.py
Labels: tests, bot:chronographer:skip

#937 Remove conflicting type in docstring
  src/ansible_navigator/utils.py
Labels: bot:chronographer:skip

#948 Notification in `run`: Preparing for automation, please hold on
  docs/changelog-fragments.d/948.feature.md
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:provided

#949 Rename App to ActionBase
  src/ansible_navigator/action_base.py
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/sample_working.py
  src/ansible_navigator/actions/stdout.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/welcome.py
Labels: bot:chronographer:skip

#936 Add spell checking (cspell) to pre-commit (as optional)
  .config/dictionary.txt
  .pre-commit-config.yaml
  cspell.config.yaml
  tox.ini
Labels: bot:chronographer:skip

#946 Normalize stdout return from actions
  src/ansible_navigator/action_defs.py
  src/ansible_navigator/actions/__init__.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/cli.py
  tests/integration/_action_run_test.py
  tests/integration/test_stdout_exit_codes.py
Labels: bot:chronographer:skip

#953 Docstring updates in action_base (D/DAR)
  .flake8
  src/ansible_navigator/action_base.py
Labels: bot:chronographer:skip

#955 Convert ExitMessage to a dataclass
  src/ansible_navigator/utils.py
Labels: bot:chronographer:skip

#954 Convert UIConfig to dataclass, correcting docstring (D/DAR)
  .flake8
  src/ansible_navigator/ui_framework/ui_config.py
Labels: bot:chronographer:skip

#958 A few `Union[None...` to `Optional` type changes
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/steps.py
Labels: bot:chronographer:skip

#967 Remove type ignore, clarify others in tests
  tests/integration/_action_run_test.py
  tests/integration/_tmux_session.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/test_circular_imports.py
Labels: bot:chronographer:skip

#956 Convert SettingsEntry to a dataclass
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
Labels: bot:chronographer:skip

#962 Clarify E203 ignore in flake8 configuration file
  .flake8
Labels: bot:chronographer:skip

#943 Use full URL for documentation links
  CHANGELOG.md
  README.md
  docs/changelog-fragments.d/README.md
  docs/conf.py
Labels: bot:chronographer:skip

#939 Add types to `colorize.py`
  .flake8
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_defs.py
  src/ansible_navigator/ui_framework/ui.py
  tests/unit/ui_framework/test_colorize.py
Labels: bot:chronographer:skip

#973 Ensure tox configuration focuses on docstrings and developer experience
  .darglint
  .flake8
  .pre-commit-config.yaml
  src/ansible_navigator/ui_framework/form_handler_text.py
  test-requirements.txt
  tox.ini
Labels: bot:chronographer:skip

#974 Set the python version for lint-candidates to 3.10 in GHA
  .github/workflows/tox.yml
Labels: bot:chronographer:skip

#975 Add codecov decline threshold of up to .3%
  codecov.yml
Labels: bot:chronographer:skip

#978 [meta][pylint] ignore too-few-public-methods
  pyproject.toml
  share/ansible_navigator/utils/catalog_collections.py
  share/ansible_navigator/utils/image_introspect.py
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/filter.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/quit.py
  src/ansible_navigator/actions/refresh.py
  src/ansible_navigator/actions/rerun.py
  src/ansible_navigator/actions/save.py
  src/ansible_navigator/actions/select.py
  src/ansible_navigator/actions/serialize_json.py
  src/ansible_navigator/actions/serialize_yaml.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/form_handler_information.py
  src/ansible_navigator/ui_framework/form_handler_working.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/sentinels.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/collections/test_direct_interactive_ee.py
  tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py
  tests/integration/actions/collections/test_direct_interactive_noee.py
  tests/integration/actions/collections/test_welcome_interactive_ee.py
  tests/integration/actions/collections/test_welcome_interactive_noee.py
Labels: bot:chronographer:skip

#979 Move mypy configuration to mypy.ini
  .pre-commit-config.yaml
  cspell.config.yaml
  mypy.ini
Labels: bot:chronographer:skip

#980 Add jinja2 to pre-commit mypy dependencies
  .pre-commit-config.yaml
  src/ansible_navigator/utils.py
Labels: bot:chronographer:skip

#981 Add pytest to mypy dependencies in pre-commit
  .pre-commit-config.yaml
  tests/integration/actions/run_unicode/base.py
  tests/unit/test_yaml.py
Labels: bot:chronographer:skip

#983 Remove mypy txt report
  .pre-commit-config.yaml
  mypy.ini
Labels: bot:chronographer:skip

#982 Add sphinx to mypy deps in pre-commit and test-requirements
  .pre-commit-config.yaml
  docs/conf.py
  test-requirements.txt
Labels: bot:chronographer:skip

#993 Ignore PRs from any GitHub apps in Chronographer
  .github/chronographer.yml
Labels: tests, bot:chronographer:skip

#985 Add constant colors and decorations for the UI, implement in inventory action.
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/ui_framework/__init__.py
  src/ansible_navigator/ui_framework/ui_constants.py
Labels: bot:chronographer:skip

#941 Switch exec command to a postional
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/1.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/2.json
  tests/fixtures/integration/actions/exec/test_stdout_config_cli.py/test/3.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/1.json
  tests/fixtures/integration/actions/exec/test_stdout_config_file.py/test/2.json
  tests/fixtures/integration/actions/exec/test_stdout_vault.py/test/0.json
  tests/fixtures/integration/actions/exec/test_stdout_vault.py/test/1.json
  tests/fixtures/integration/actions/exec/test_stdout_vault.py/test/2.json
  tests/fixtures/integration/actions/exec/test_stdout_vault.py/test/3.json
  tests/fixtures/integration/actions/exec/test_stdout_vault.py/test/4.json
  tests/fixtures/integration/actions/exec/test_stdout_vault.py/test/5.json
  tests/integration/actions/exec/test_stdout_cli.py
  tests/integration/actions/exec/test_stdout_file.py
  tests/integration/actions/exec/test_stdout_vault.py
  tests/unit/actions/test_exec.py
Labels: bot:chronographer:skip

#995 Limit use of `_version.py` to one location
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/parser.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
Labels: bot:chronographer:skip

#988 Rework KVS with types and extend MutableMapping instead of dict
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/utils/__init__.py
  src/ansible_navigator/utils/functions.py
  src/ansible_navigator/utils/key_value_store.py
  tests/unit/utils/conftest.py
  tests/unit/utils/test_functions.py
  tests/unit/utils/test_key_value_store.py
Labels: bot:chronographer:skip

#997 Follow up to KeyValueStore PR (pylint, docstrings, spelling) (D/DAR)
  .flake8
  src/ansible_navigator/utils/key_value_store.py
  tests/unit/utils/__init__.py
  tests/unit/utils/conftest.py
  tests/unit/utils/test_key_value_store.py
Labels: bot:chronographer:skip

#986 Application Configuration to dataclass
  docs/conf.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  tests/unit/configuration_subsystem/test_mode_subcommand_action.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
Labels: bot:chronographer:skip

#906 Migrate to pathlib in `catalog_collections`
  share/ansible_navigator/utils/catalog_collections.py
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/10.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/12.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/0.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/12.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/11.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/13.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/13.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/9.json
Labels: bot:chronographer:skip

#1004 Centralize json dump and dumps
  docs/conf.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/serialize.py
Labels: bot:chronographer:skip

#1002 Reorder import of key_value_store
  share/ansible_navigator/utils/catalog_collections.py
Labels: bot:chronographer:skip

#1000 Remove inconsistent colon in README.md (PR #1000!)
  README.md
Labels: bot:chronographer:skip

#1005 Align the RTD config file to the schema, upgrade to python 3.10
  .readthedocs.yml
Labels: documentation, bot:chronographer:skip

#1006 Incremental implementation of prettier
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#1007 Add toml support to prettier
  .pre-commit-config.yaml
  pyproject.toml
Labels: bot:chronographer:skip

#1010 Remove ignore missing imports for mypy
  .pre-commit-config.yaml
  mypy.ini
Labels: bot:chronographer:skip

#1011 Centralize mypy `ignore[import]` statements
  docs/_ext/single_sourced_data.py
  docs/conf.py
  mypy.ini
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/tm_tokenize/reg.py
Labels: bot:chronographer:skip

#1001 Fix incorrect version reporting in changelogs
  docs/conf.py
  mypy.ini
  tox.ini
Labels: bot:chronographer:skip

#1012 Move _yaml to `utils/serialize.py`
  src/ansible_navigator/_yaml.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/serialize.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
  tests/unit/ui_framework/test_colorize.py
  tests/unit/utils/test_serialize_yaml.py
Labels: bot:chronographer:skip

#1015 Fix docstring in `test_serialize_yaml.py` in file (D/DAR)
  .flake8
  tests/unit/utils/test_serialize_yaml.py
Labels: bot:chronographer:skip

#1019 Fix color resolution issue
  src/ansible_navigator/ui_framework/colorize.py
  tests/unit/ui_framework/test_colorize.py
Labels: bot:chronographer:skip

#1023 Prefer `thing.get(key)` over `thing[key]` in ui.py
  src/ansible_navigator/ui_framework/ui.py
Labels: bot:chronographer:skip

#1025 Remove docstring first check from pre-commit
  .pre-commit-config.yaml
Labels: bot:chronographer:skip
