Repository ansible/ansible-navigator, pull requests merged in 2022-03, with the labels that each got.

#968 Introduce small delay in stdout dequeue read loop
  docs/changelog-fragments.d/968.bugfix.md
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:provided

#952 Add pull_arguments
  docs/changelog-fragments.d/952.feature.md
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/utils/functions.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/unit/configuration_subsystem/data.py
  tests/unit/image_manager/test_image_puller.py
Labels: bot:chronographer:provided

#1028 Switch to internal shlex_join
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/runner/command_base.py
Labels: bot:chronographer:skip

#1029 Move pull_policy to pull.policy
  docs/changelog-fragments.d/1029.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
Labels: bot:chronographer:provided

#1030 Update utils import statements to point to functions
  docs/_ext/single_sourced_data.py
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/__init__.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/test_image_introspection.py
  tests/unit/utils/test_functions.py
Labels: bot:chronographer:skip

#1027 Auto format markdown with prettier
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/security_bug_report.md
  .prettierignore
  docs/changelog-fragments.d/1029.breaking.md
  docs/changelog-fragments.d/459.feature.md
  docs/changelog-fragments.d/526.feature.md
  docs/changelog-fragments.d/558.misc.md
  docs/changelog-fragments.d/736.internal.md
  docs/changelog-fragments.d/968.bugfix.md
  docs/contributing/code_of_conduct.md
  docs/contributing/guidelines.md
  docs/contributing/security.md
  docs/faq.md
  docs/index.md
  docs/installation.md
Labels: bot:chronographer:skip

#1034 Allow prettier to format security.md
  .github/SECURITY.md
  .prettierignore
Labels: bot:chronographer:skip

#1039 Switch from `SimpleNamespace` to `dataclass` for `Internals`
  docs/conf.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
Labels: bot:chronographer:skip

#1041 Test auto-update outstanding PRs
  .github/workflows/autoupdate.yaml
Labels: bot:chronographer:skip

#1042 Test: Small change to test auto
  src/ansible_navigator/cli.py
Labels: bot:chronographer:skip

#1044 Rename action, add label
  .github/workflows/autoupdate.yml
Labels: bot:chronographer:skip

#1046 Test: Small change to file
  src/ansible_navigator/cli.py
Labels: bot:chronographer:skip

#1047 Test: Remove all changes
  .github/workflows/autoupdate.yml
  src/ansible_navigator/cli.py
Labels: bot:chronographer:skip

#1043 Clear tmux screen in case subsequent tests produce the same output
  tests/integration/_tmux_session.py
Labels: bot:chronographer:skip

#1038 Switch from `SimpleNamespace` to frozen `dataclass` in defintions
  src/ansible_navigator/configuration_subsystem/definitions.py
Labels: bot:chronographer:skip

#1036 Switch from `SimpleNamespace` to `dataclass` in command runner
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/image_manager/inspector.py
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/2.json
Labels: bot:chronographer:skip

#1037 Switch from `SimpleNamespace` to `dataclass` in puller
  src/ansible_navigator/image_manager/puller.py
Labels: bot:chronographer:skip

#1024 Define `CursesLine` and `CursesLines` as NewType (`:settings` related)
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_defs.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
Labels: bot:chronographer:skip

#1035 cspell maintenance
  .config/dictionary.txt
  cspell.config.yaml
Labels: bot:chronographer:skip

#1049 Fixed : broken changlog link #970
  CHANGELOG.md
Labels: bot:chronographer:skip

#1050 Normalize optional types
  mypy.ini
  share/ansible_navigator/utils/image_introspect.py
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/__init__.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form_presenter.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/validators.py
  src/ansible_navigator/utils/functions.py
  src/ansible_navigator/utils/serialize.py
  tests/integration/_interactions.py
  tests/integration/_tmux_session.py
  tests/integration/actions/exec/base.py
  tests/unit/actions/test_run.py
Labels: bot:chronographer:skip

#1026 Building dataclass `TypedStep` into steps.py and building `TypedStep` unit tests (`:settings` related)
  docs/conf.py
  src/ansible_navigator/steps.py
  tests/unit/test_typestep.py
Labels: bot:chronographer:skip

#1053 Restore sys.exit with exit code
  src/ansible_navigator/cli.py
  tests/integration/test_stdout_exit_codes.py
Labels: bot:chronographer:skip

#1031 Add ability to transform settings to a presentable dataclass (`:settings` related)
  docs/conf.py
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/configuration_subsystem/utils.py
  tests/unit/configuration_subsystem/test_presentable.py
Labels: bot:chronographer:skip

#1014 `dataclass` serialization capabilities (`:settings` related)
  docs/conf.py
  src/ansible_navigator/ui_framework/__init__.py
  src/ansible_navigator/ui_framework/content_defs.py
  src/ansible_navigator/utils/compatibility.py
  src/ansible_navigator/utils/serialize.py
  test-requirements.txt
  tests/unit/utils/test_serialize_dataclass.py
Labels: bot:chronographer:skip

#1033 Convert percentages, dataclass capable (`:settings` related)
  src/ansible_navigator/ui_framework/content_defs.py
  src/ansible_navigator/ui_framework/utils.py
  tests/unit/ui_framework/test_progress_bar.py
Labels: bot:chronographer:skip

#1056 Limit the use of typing-extensions to just TYPE_CHECKING
  src/ansible_navigator/ui_framework/content_defs.py
  src/ansible_navigator/utils/compatibility.py
Labels: bot:chronographer:skip

#1057 Test basic stdout functionality without test-requirements
  .github/workflows/tox.yml
  src/ansible_navigator/command_runner/command_runner.py
  tests/smoke/no_test_dependencies.py
  tox.ini
Labels: bot:chronographer:skip

#1058 Auto-select mode based on parameter or subcommand capabilities
  docs/changelog-fragments.d/1058.feature.md
  src/ansible_navigator/action_base.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/initialization.py
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/7.json
  tests/integration/actions/builder/test_stdout_tmux.py
  tests/integration/actions/config/test_stdout_tmux.py
  tests/integration/actions/doc/test_stdout.py
  tests/integration/actions/inventory/test_stdout_tmux.py
  tests/integration/actions/run/test_stdout_tmux.py
  tests/smoke/no_test_dependencies.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_configurator.py
  tests/unit/configuration_subsystem/test_internals.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_mode_subcommand_action.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/test_cli.py
Labels: bot:chronographer:skip

#1062 Collections fix, always mount the doc cache
  docs/changelog-fragments.d/1062.bugfix.md
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/initialization.py
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/1.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/2.json
  tests/integration/actions/collections/test_direct_interactive_ee_with_volmount.py
Labels: bot:chronographer:provided

#1060 Docstring fixes for src/ansible_navigator/runner (D/DAR)
  .flake8
  src/ansible_navigator/runner/__init__.py
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/runner/command_base.py
Labels: documentation, bot:chronographer:skip

#1065 Docstring fixes for image_manager (D/DAR)
  .flake8
  src/ansible_navigator/image_manager/__init__.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/image_manager/puller.py
Labels: bot:chronographer:skip

#1067 Docstring fixes for src/ansible_navigator/command_runner (D/DAR)
  .flake8
  src/ansible_navigator/command_runner/__init__.py
  src/ansible_navigator/command_runner/command_runner.py
Labels: documentation, bot:chronographer:skip

#1070 Quick fixes in docstring (D/DAR)
  share/ansible_navigator/utils/image_introspect.py
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/builder.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/quit.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/sample_form.py
  src/ansible_navigator/actions/sample_notification.py
  src/ansible_navigator/actions/stdout.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/runner/ansible_config.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command_base.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/functions.py
  src/ansible_navigator/utils/serialize.py
  tests/unit/test_circular_imports.py
Labels: bot:chronographer:skip

#1068 Docstring fixes for src/ansible_navigator/steps.py (D/DAR)
  .flake8
  src/ansible_navigator/steps.py
Labels: documentation, bot:chronographer:skip

#1071 Docstring fixes for src/ansible_navigator/initialization.py (D/DAR)
  .flake8
  src/ansible_navigator/initialization.py
Labels: documentation, bot:chronographer:skip

#1054 Migration to serialization (`:settings` related)
  docs/conf.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/serialize.py
  tests/unit/actions/test_run.py
  tests/unit/ui_framework/test_colorize.py
  tests/unit/utils/test_serialize_yaml.py
  tests/unit/utils/test_unserializable.py
Labels: bot:chronographer:skip

#1074 Set source to `Constants.AUTO` for container engine when automatically set
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/configuration_subsystem/test_precedence.py
Labels: bot:chronographer:skip

#1072 Include dependency versions and locations in debug log
  .pre-commit-config.yaml
  src/ansible_navigator/cli.py
  tests/unit/test_cli.py
Labels: bot:chronographer:skip

#1075 Switch from 'label' to 'options' for ee volmount
  docs/changelog-fragments.d/1075.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/unit/configuration_subsystem/post_processors/test_execution_environment_volume_mounts.py
  tests/unit/configuration_subsystem/utils.py
Labels: bot:chronographer:provided

#1077 Move class definitions out of post processor into definitions
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
Labels: bot:chronographer:skip

#1073 Implement the `:settings` subcommand
  docs/changelog-fragments.d/957.feature.md
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/serialize.py
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/9.json
  tests/integration/actions/settings/__init__.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/settings/test_direct_interactive_ee.py
  tests/integration/actions/settings/test_direct_interactive_noee.py
  tests/integration/actions/settings/test_stdout_tmux.py
  tests/integration/actions/settings/test_welcome_interactive_ee.py
  tests/integration/actions/settings/test_welcome_interactive_noee.py
  tests/unit/actions/settings/__init__.py
  tests/unit/actions/settings/test_settings.py
Labels: bot:chronographer:provided

#1078 Basic IANA TZ support
  .config/dictionary.txt
  .pre-commit-config.yaml
  setup.cfg
  src/ansible_navigator/utils/compatibility.py
  src/ansible_navigator/utils/functions.py
  tests/unit/utils/test_functions.py
Labels: bot:chronographer:skip

#940 Add spell checking (cspell) to pre-commit (as required)
  .pre-commit-config.yaml
Labels: bot:chronographer:skip

#1085 Enable the use of `time_zone` for playbook artifact creation
  .pre-commit-config.yaml
  docs/changelog-fragments.d/1085.breaking.md
  docs/changelog-fragments.d/1085.feature.md
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/actions/run/__init__.py
  tests/unit/actions/run/test_artifact.py
  tests/unit/actions/run/test_runner_async.py
  tests/unit/actions/test_run.py
  tests/unit/configuration_subsystem/post_processors/test_playbook_artifact_save_as.py
Labels: bot:chronographer:provided

#1083 Change to path, type and document update_fixtures
  tests/integration/_common.py
Labels: bot:chronographer:skip

#1086 Enable the use of `time_zone` for logging
  docs/changelog-fragments.d/1086.feature.md
  src/ansible_navigator/cli.py
  tests/unit/logging/__init__.py
  tests/unit/logging/test_append.py
  tests/unit/logging/test_time_zone.py
  tests/unit/test_log_append.py
Labels: bot:chronographer:provided

#1092 Rename TestData to Scenario
  tests/unit/actions/run/test_artifact.py
  tests/unit/actions/run/test_runner_async.py
  tests/unit/logging/test_append.py
  tests/unit/logging/test_time_zone.py
Labels: bot:chronographer:skip

#1094 Move logger initialization out of cli.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/logging.py
Labels: bot:chronographer:skip

#1093 Add `settings --schema` support
  .pre-commit-config.yaml
  docs/changelog-fragments.d/1093.feature.md
  mypy.ini
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/configuration_subsystem/schema.py
  src/ansible_navigator/configuration_subsystem/transform.py
  test-requirements.txt
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/fixtures/unit/configuration_subsystem/ansible-navigator_no_app.yml
  tests/integration/actions/settings/test_stdout_tmux.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/configuration_subsystem/test_json_schema.py
Labels: bot:chronographer:provided

#1098 Add release drafting pipelines
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
Labels: bot:chronographer:skip

#1100 Move playbook to playbook.path
  docs/changelog-fragments.d/1100.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/schema.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
Labels: bot:chronographer:provided, major

#1099 Runtime JSON Schema validation of settings file
  docs/changelog-fragments.d/1099.feature.md
  setup.cfg
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/utils/json_schema.py
  test-requirements.txt
  tests/fixtures/integration/actions/replay/ansible-navigator.yml
  tests/fixtures/integration/execution_environment/ansible-navigator_empty.yml
  tests/fixtures/integration/execution_environment_image/ansible-navigator_empty.yml
  tests/fixtures/integration/pass_environment_variable/ansible-navigator_empty.yml
  tests/fixtures/integration/set_environment_variable/ansible-navigator_empty.yml
  tests/fixtures/unit/cli/ansible-navigator.yml
  tests/fixtures/unit/cli/ansible-navigator_empty.yml
  tests/fixtures/unit/configuration_subsystem/ansible-navigator_empty.yml
  tests/fixtures/unit/configuration_subsystem/ansible-navigator_unknown_key.yml
  tests/integration/settings_from_cli/__init__.py
  tests/integration/settings_from_cli/test_json_schema_errors.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_broken_settings.py
  tests/unit/configuration_subsystem/test_internals.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_json_schema.py
  tests/unit/test_cli.py
Labels: enhancement, bot:chronographer:provided

#1101 Update `:config` to look more like `:settings`
  docs/changelog-fragments.d/1101.feature.md
  src/ansible_navigator/actions/config.py
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/config/test_stdout_tmux.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_param_use.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_param_use.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/3.json
  tests/integration/actions/config/base.py
  tests/integration/actions/config/test_direct_interactive_noee.py
  tests/integration/actions/config/test_welcome_interactive_noee.py
  tests/integration/actions/config/test_welcome_interactive_param_use.py
  tests/integration/actions/config/test_welcome_interactive_specified_config.py
  tests/unit/actions/test_config.py
Labels: enhancement, bot:chronographer:provided

#1102 Move `ansible.config` to `ansible.config.path`
  docs/changelog-fragments.d/1102.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/schema.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
Labels: bot:chronographer:skip, major

#1103 Move `ansible.invetories` to `ansible.inventory.paths`
  docs/changelog-fragments.d/1103.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/schema.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
Labels: bot:chronographer:provided, major

#1104 Move `help_*` out of settings root
  docs/changelog-fragments.d/1104.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/schema.py
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/unit/configuration_subsystem/test_json_schema.py
Labels: bot:chronographer:provided, major

#1095 Docstring fixes for src/ansible_navigator/cli.py (D/DAR)
  .flake8
  src/ansible_navigator/cli.py
Labels: documentation, bot:chronographer:skip

#1108 Move `documentation` to `ansible.doc` in settings file
  docs/changelog-fragments.d/1106.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/schema.py
  tests/fixtures/unit/cli/ansible-navigator.yml
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/unit/configuration_subsystem/test_json_schema.py
Labels: bot:chronographer:provided, major

#1106 Add `settings --sample`
  MANIFEST.in
  docs/changelog-fragments.d/1106.feature.md
  setup.cfg
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/schema.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/package_data/__init__.py
  src/ansible_navigator/package_data/settings-sample.template.yml
  src/ansible_navigator/utils/compatibility.py
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/actions/settings/test_stdout_tmux.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/configuration_subsystem/test_json_schema.py
  tests/unit/configuration_subsystem/test_settings_sample.py
Labels: enhancement, bot:chronographer:skip

#1109 Refactor `:open_file`
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/utils/serialize.py
Labels: bot:chronographer:skip

#1110 Basic `--mode stdout` for images
  docs/changelog-fragments.d/1110.feature.md
  src/ansible_navigator/actions/images.py
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/0.json
  tests/integration/_interactions.py
  tests/integration/actions/images/test_stdout_tmux.py
Labels: enhancement, bot:chronographer:provided

#1112 Show warning messages in TUI for invalid arguments
  docs/changelog-fragments.d/1112.bugfix.md
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/utils/functions.py
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/20.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/21.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/17.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/18.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/19.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/20.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/21.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/22.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/23.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_ee_with_volmount.py/test/24.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/20.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/21.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/20.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/21.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_ee.py/test/25.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/20.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/21.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/25.json
  tests/integration/_interactions.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run_unicode/base.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/templar/base.py
Labels: bug, bot:chronographer:provided

#1113 Switch to `ANSIBLE_INVENTORY` for inventory environment variable
  docs/changelog-fragments.d/1113.breaking.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
Labels: bug, bot:chronographer:provided

#1117 Rename logging to logger
  src/ansible_navigator/cli.py
  src/ansible_navigator/logger.py
  tests/unit/logger/__init__.py
  tests/unit/logger/test_append.py
  tests/unit/logger/test_time_zone.py
Labels: bot:chronographer:skip

#1107 Docstring fixes for src/ansible-navigator/actions/run.py
  .flake8
  src/ansible_navigator/actions/run.py
Labels: documentation, bot:chronographer:skip

#1121 Wrap all action calls with `try/except`
  src/ansible_navigator/actions/_actions.py
  tests/integration/_cli2runner.py
  tests/unit/actions/collections/test_collection_doc_cache_path.py
Labels: bot:chronographer:skip

#1122 Ignore artifacts created during tests in test_ee directory
  tests/fixtures/common/builder/test_ee/context/.gitignore
Labels: bot:chronographer:skip

#1111 Use inventory if configured in `ansible.cfg`
  docs/changelog-fragments.d/1111.feature.md
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/utils.py
  tests/conftest.py
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_using_cfg.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_using_cfg.py/test/1.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_using_cfg.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_using_cfg.py/test/1.json
  tests/fixtures/integration/actions/inventory/using_ansible_cfg/ansible.cfg
  tests/fixtures/integration/actions/inventory/using_ansible_cfg/inventory.yml
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/run/test_stdout_tmux.py/test/7.json
  tests/fixtures/integration/actions/run/using_ansible_cfg/ansible.cfg
  tests/fixtures/integration/actions/run/using_ansible_cfg/inventory.yml
  tests/fixtures/integration/actions/run/using_ansible_cfg/site.yml
  tests/integration/actions/inventory/base.py
  tests/integration/actions/inventory/test_direct_interactive_ee_using_cfg.py
  tests/integration/actions/inventory/test_direct_interactive_noee_using_cfg.py
  tests/integration/actions/run/test_stdout_tmux.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/post_processors/test_inventory.py
  tests/unit/configuration_subsystem/test_ansible_config_parse.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tox.ini
Labels: bug, bot:chronographer:provided

#1120 Build docs from scratch everytime
  tox.ini
Labels: bot:chronographer:skip

#1119 deepcopy `NavigatorConfiguration` in the tests
  tests/unit/configuration_subsystem/post_processors/test_execution_environment_volume_mounts.py
  tests/unit/configuration_subsystem/post_processors/test_playbook_artifact_save_as.py
  tests/unit/configuration_subsystem/post_processors/test_time_zone.py
  tests/unit/configuration_subsystem/test_configurator.py
  tests/unit/configuration_subsystem/test_json_schema.py
  tests/unit/configuration_subsystem/test_settings_sample.py
Labels: tests, bot:chronographer:skip

#1123 Fix version placement in JSON Schema
  src/ansible_navigator/configuration_subsystem/transform.py
Labels: bug, bot:chronographer:skip

#1125 Move schema into package data directory
  .config/dictionary.txt
  src/ansible_navigator/configuration_subsystem/schema.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/package_data/settings-schema.partial.json
Labels: bot:chronographer:skip

#1131 Remove check for inventory file path
  src/ansible_navigator/actions/run.py
Labels: bot:chronographer:skip

#1127 Move `welcome.md` and `help.md` to `package_data` from `share` directory
  .pre-commit-config.yaml
  .prettierignore
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/welcome.py
  src/ansible_navigator/package_data/help.md
  src/ansible_navigator/package_data/welcome.md
Labels: bot:chronographer:skip, skip-changelog

#1134 Add version to schema title
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/package_data/settings-schema.partial.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/integration/actions/settings/test_stdout_tmux.py
Labels: bot:chronographer:skip

#1128 Change `inventory.paths` to `inventory.entries`
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/package_data/settings-sample.template.yml
  src/ansible_navigator/package_data/settings-schema.partial.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
Labels: bot:chronographer:skip

#1129 Update changelog for #1103 to reflect inventory.entries
  docs/changelog-fragments.d/1103.breaking.md
Labels: bot:chronographer:skip

#1114 Refactor Cli2Runner integration tests
  tests/integration/_cli2runner.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
Labels: bot:chronographer:skip

#1126 Add `ansible.cfg` path to each entry in `:config`
  docs/changelog-fragments.d/1126.feature.md
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/utils.py
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee_using_cfg.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee_using_cfg.py/test/1.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/config/using_ansible_cfg/ansible.cfg
  tests/integration/actions/config/base.py
  tests/integration/actions/config/test_direct_interactive_ee_using_cfg.py
  tests/unit/configuration_subsystem/test_ansible_config_parse.py
Labels: enhancement, bot:chronographer:provided

#1137 Print to stdout in color for `:settings`
  docs/changelog-fragments.d/1137.feature.md
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/utils/print.py
  src/ansible_navigator/utils/serialize.py
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/unit/configuration_subsystem/test_json_schema.py
  tests/unit/utils/test_unserializable.py
Labels: enhancement, bot:chronographer:provided

#1139 Docstring/linting/constant updates for `:lint` action (D/DAR)
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/runner/command_base.py
Labels: documentation, bot:chronographer:skip

#1138 Add the `--details` flag for `ansible-navigator images` for stdout
  docs/changelog-fragments.d/1138.feature.md
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/package_data/settings-sample.template.yml
  src/ansible_navigator/package_data/settings-schema.partial.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/3.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/actions/images/test_stdout_tmux.py
  tests/unit/configuration_subsystem/data.py
  tests/unit/configuration_subsystem/test_invalid_params.py
Labels: enhancement, bot:chronographer:provided

#1132 Catch unable to parse inventory messages
  src/ansible_navigator/actions/inventory.py
  tests/fixtures/integration/actions/inventory/broken_inventory.ini
  tests/fixtures/integration/actions/inventory/broken_inventory.yml
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_errors.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_errors.py/test/1.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_errors.py/test/2.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_errors.py/test/3.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_errors.py/test/4.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_errors.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_errors.py/test/1.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_errors.py/test/2.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_errors.py/test/3.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_errors.py/test/4.json
  tests/integration/actions/inventory/test_direct_interactive_ee_errors.py
  tests/integration/actions/inventory/test_direct_interactive_noee_errors.py
Labels: bot:chronographer:skip

#1130 Add stdout mode support for collections
  docs/changelog-fragments.d/580.feature.md
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/actions/collections.py
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/1.json
  tests/integration/actions/collections/test_stdout_tmux.py
Labels: enhancement, bot:chronographer:provided

#1140 Add refresh to ansible-lint
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/utils/functions.py
Labels: bot:chronographer:skip

#1141 Collection updates (lint + typing)
  src/ansible_navigator/actions/collections.py
  tests/integration/actions/collections/test_stdout_tmux.py
Labels: bot:chronographer:skip

#1147 Redirect to `stdout` if a playbook completes without any tasks
  src/ansible_navigator/actions/run.py
Labels: AAP, bot:chronographer:skip

#1146 Disable color if device is not a TTY
  .config/dictionary.txt
  src/ansible_navigator/utils/print.py
Labels: AAP, bot:chronographer:skip

#1145 Allow collections to syntax highlight stdout
  docs/changelog-fragments.d/1145.feature.md
  src/ansible_navigator/actions/collections.py
Labels: enhancement, bot:chronographer:provided

#1144 Allow images to syntax highlight stdout
  docs/changelog-fragments.d/1144.feature.md
  src/ansible_navigator/actions/images.py
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/3.json
  tests/integration/actions/images/test_stdout_tmux.py
  tests/integration/actions/inventory/test_direct_interactive_noee_errors.py
Labels: enhancement, bot:chronographer:provided

#1150 Config subsystem docstrings (D/DAR) (again)
  .flake8
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/parser.py
Labels: bot:chronographer:skip

#1148 Add `to_effective` and `to_sources` with tests
  docs/conf.py
  src/ansible_navigator/configuration_subsystem/__init__.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/configuration_subsystem/utils.py
  src/ansible_navigator/utils/dict_merge.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_json_schema.py
  tests/unit/configuration_subsystem/test_settings_effective.py
  tests/unit/configuration_subsystem/test_settings_sample.py
  tests/unit/configuration_subsystem/test_settings_sources.py
  tests/unit/utils/test_dict_merge.py
Labels: bot:chronographer:skip

#1151 Add `--effective` and `--sources` to `settings`
  docs/changelog-fragments.d/1151.feature.md
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/package_data/settings-sample.template.yml
  src/ansible_navigator/package_data/settings-schema.partial.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/actions/settings/test_stdout_tmux.py
  tests/unit/configuration_subsystem/data.py
Labels: enhancement, bot:chronographer:provided

#1149 Drop python 3.6 and 3.7 support
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  docs/_ext/single_sourced_data.py
  docs/changelog-fragments.d/1149.breaking.md
  setup.cfg
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/compatibility.py
Labels: bot:chronographer:provided, major, skip-changelog

#1156 Upgrade to latest black
  .pre-commit-config.yaml
Labels: bot:chronographer:skip, skip-changelog

#1158 Preserve font style
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_defs.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/ui_constants.py
  tests/unit/ui_framework/test_colorize.py
Labels: bot:chronographer:skip

#1152 Add settings information to artifact file
  docs/changelog-fragments.d/1152.feature.md
  src/ansible_navigator/actions/run.py
  tests/unit/actions/run/test_artifact.py
Labels: enhancement, AAP, bot:chronographer:provided

#1153 `ansible-navigator --diagnostics` produces a ton of diagnostic information for troubleshooting
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/introspect.py
  src/ansible_navigator/image_manager/introspector.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/utils/ansi.py
  tests/conftest.py
  tests/integration/diagnostics/__init__.py
  tests/integration/diagnostics/test_from_cli.py
  tests/unit/configuration_subsystem/conftest.py
Labels: AAP, bot:chronographer:skip

#1164 ui_framework init and curses_defs doc string fixes (D/DAR)
  .flake8
  src/ansible_navigator/ui_framework/__init__.py
  src/ansible_navigator/ui_framework/curses_defs.py
Labels: documentation, bot:chronographer:skip

#1166 Small fixes for 2.9 (ansible version, collections list)
  share/ansible_navigator/utils/image_introspect.py
  src/ansible_navigator/image_manager/introspect.py
Labels: bot:chronographer:skip

#1165 Add `--playbook-dir` to inventory commands
  src/ansible_navigator/actions/inventory.py
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_using_plugin.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_ee_using_plugin.py/test/1.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_using_plugin.py/test/0.json
  tests/fixtures/integration/actions/inventory/test_direct_interactive_noee_using_plugin.py/test/1.json
  tests/fixtures/integration/actions/inventory/using_plugin/ansible.cfg
  tests/fixtures/integration/actions/inventory/using_plugin/collections/ansible_collections/test/test/plugins/inventory/test.py
  tests/fixtures/integration/actions/inventory/using_plugin/test_inventory.yml
  tests/integration/actions/inventory/test_direct_interactive_ee_using_plugin.py
  tests/integration/actions/inventory/test_direct_interactive_noee_using_plugin.py
Labels: bot:chronographer:skip

#1163 Add support for `doc --list` and other doc paramters
  docs/changelog-fragments.d/1163.bugfix.md
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/integration/actions/doc/test_stdout_subprocess.py
  tests/unit/configuration_subsystem/test_invalid_params.py
Labels: enhancement, bot:chronographer:provided

#1162 Remove -- from extra args (fixes a builder and config issue)
  src/ansible_navigator/configuration_subsystem/configurator.py
Labels: bot:chronographer:skip

#1170 initial go at lint tests
  tests/fixtures/integration/actions/lint/borked/playbook.yml
  tests/fixtures/integration/actions/lint/borked/roles/uh-huh/tasks/main.yml
  tests/fixtures/integration/actions/lint/borked/roles/yep/tasks/main.yml
  tests/fixtures/integration/actions/lint/no_errors/playbook.yml
  tests/fixtures/integration/actions/lint/no_errors/roles/no-errors-here/tasks/main.yml
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_no_errors_ee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/lint/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/3.json
  tests/integration/actions/lint/__init__.py
  tests/integration/actions/lint/base.py
  tests/integration/actions/lint/test_direct_interactive_ee.py
  tests/integration/actions/lint/test_direct_interactive_no_errors_ee.py
  tests/integration/actions/lint/test_stdout_tmux.py
  tests/integration/actions/lint/test_welcome_interactive_ee.py
Labels: enhancement, bot:chronographer:skip, skip-changelog

#1169 Update command mapping table
  docs/subcommands.rst
Labels: documentation, bot:chronographer:skip

#1171 FAQ updates
  docs/faq.md
Labels: documentation, bot:chronographer:skip
