Repository ansible/ansible-navigator, pull requests merged in 2022-05, with the labels that each got.

#1217 Docstring fixes for src/ansible_navigator/ui_framework/field* (D/DAR)
  .flake8
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_option.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
Labels: documentation, bot:chronographer:skip

#1211 backquotes cli example and subcommands
  docs/_ext/single_sourced_data.py
Labels: documentation, bot:chronographer:skip

#1222 Allow compound words for python
  cspell.config.yaml
Labels: bot:chronographer:skip

#1223 Playbook status
  docs/changelog-fragments.d/1223.feature.md
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/data/ansible-navigator.json
  tests/unit/actions/run/test_artifact.py
Labels: enhancement, bot:chronographer:provided

#1220 Fix warning message issue for run action in stdout mode
  docs/changelog-fragments.d/1220.bugfix.md
  src/ansible_navigator/runner/command_async.py
Labels: bug, bot:chronographer:provided

#1225 Fix settings issue when directing to a settings file
  src/ansible_navigator/configuration_subsystem/configurator.py
Labels: bug, bot:chronographer:skip, skip-changelog

#1228 Docstring fixes for tests/integration/actions/run (D/DAR)
  .flake8
  src/ansible_navigator/data/ansible-navigator.json
  tests/integration/actions/run/__init__.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run/test_direct_interactive_ee.py
  tests/integration/actions/run/test_direct_interactive_noee.py
  tests/integration/actions/run/test_stdout_tmux.py
  tests/integration/actions/run/test_welcome_interactive_ee.py
  tests/integration/actions/run/test_welcome_interactive_noee.py
Labels: documentation, bot:chronographer:skip, impatience-allowed

#1230 Docstring fixes for tests/integration/actions/stdout (D/DAR)
  .flake8
  tests/integration/actions/stdout/__init__.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/stdout/test_direct_interactive_ee.py
  tests/integration/actions/stdout/test_direct_interactive_noee.py
  tests/integration/actions/stdout/test_welcome_interactive_ee.py
  tests/integration/actions/stdout/test_welcome_interactive_noee.py
Labels: documentation, bot:chronographer:skip, impatience-allowed

#1232 Docstring fixes for tests/integration/actions/templar (D/DAR)
  .flake8
  tests/integration/actions/templar/__init__.py
  tests/integration/actions/templar/base.py
  tests/integration/actions/templar/test_direct_interactive_ee.py
  tests/integration/actions/templar/test_direct_interactive_noee.py
  tests/integration/actions/templar/test_welcome_interactive_ee.py
  tests/integration/actions/templar/test_welcome_interactive_noee.py
Labels: documentation, bot:chronographer:skip
