Repository ansible/ansible-navigator, pull requests merged in 2023-05, with the labels that each got.

#1507 Improve custom exception naming
  pyproject.toml
  src/ansible_navigator/diagnostics.py
  tests/integration/_cli2runner.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
  tests/unit/actions/collections/test_collection_doc_cache_path.py
Labels: skip-changelog

#1506 Use `@cache` instead of `@lru_cache(maxsize=None)`
  pyproject.toml
  src/ansible_navigator/ui_framework/ui.py
Labels: skip-changelog

#1510 Avoid f-string in logging statement
  pyproject.toml
  src/ansible_navigator/actions/images.py
Labels: skip-changelog

#1498 Don't shadow builtins
  pyproject.toml
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/content_defs.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/image_manager/introspect.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/utils/key_value_store.py
  tests/integration/_interactions.py
  tests/integration/actions/images/test_stdout_tmux.py
  tests/unit/utils/test_functions.py
Labels: skip-changelog

#1513 Include only major version inside schema generation
  src/ansible_navigator/configuration_subsystem/transform.py
  src/ansible_navigator/data/ansible-navigator.json
Labels: bug

#1514 Address SIM rule
  pyproject.toml
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/back.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/data/catalog_collections.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_handler_button.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/ui_framework/validators.py
  src/ansible_navigator/utils/dict_merge.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/serialize.py
  src/ansible_navigator/utils/version_migration/definitions.py
  tests/integration/_common.py
  tests/integration/_tmux_session.py
  tests/integration/actions/doc/base.py
  tests/unit/actions/settings/test_settings.py
  tests/unit/configuration_subsystem/test_entries_sanity.py
  tests/unit/configuration_subsystem/test_invalid_params.py
Labels: skip-changelog

#1511 Address implicit and explicit string concatenation
  pyproject.toml
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/collections.py
  tests/integration/actions/replay/test_direct_interactive_ee.py
  tests/integration/actions/stdout/test_direct_interactive_ee.py
  tests/integration/actions/stdout/test_direct_interactive_noee.py
  tests/unit/actions/test_exec.py
Labels: skip-changelog

#1516 Exception must not use string or f-string literal
  pyproject.toml
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/tm_tokenize/compiler.py
  src/ansible_navigator/tm_tokenize/rules.py
  src/ansible_navigator/utils/dict_merge.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/serialize.py
  tests/conftest.py
  tests/integration/_common.py
  tests/integration/_tmux_session.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/exec/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/settings/base.py
  tests/integration/settings_from_cli/test_json_schema_errors.py
  tests/smoke/no_test_dependencies.py
  tests/unit/actions/run/test_artifact.py
Labels: skip-changelog

#1517 Address BLE rule
  pyproject.toml
  src/ansible_navigator/cli.py
  src/ansible_navigator/data/catalog_collections.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/introspect.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/utils/version_migration/definitions.py
  src/ansible_navigator/version.py
Labels: skip-changelog

#1518 Disable `pylint` checks that overlap with `ruff`
  pyproject.toml
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/actions/doc.py
  src/ansible_navigator/actions/filter.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/quit.py
  src/ansible_navigator/actions/rerun.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/actions/serialize_json.py
  src/ansible_navigator/actions/serialize_yaml.py
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/actions/template.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/utils.py
  src/ansible_navigator/data/catalog_collections.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/introspect.py
  src/ansible_navigator/initialization.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/field_curses_information.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form_handler_button.py
  src/ansible_navigator/ui_framework/form_handler_information.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/form_handler_working.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/validators.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/version_migration/definitions.py
  src/ansible_navigator/utils/version_migration/migrate.py
  src/ansible_navigator/version.py
  tests/conftest.py
  tests/defaults.py
  tests/fixtures/common/collections/ansible_collections/company_name/coll_1/plugins/lookup/lookup_1.py
  tests/fixtures/common/collections/ansible_collections/company_name/coll_2/plugins/lookup/lookup_2.py
  tests/fixtures/common/collections/ansible_collections/company_name/coll_2/plugins/modules/mod_2.py
  tests/integration/_action_run_test.py
  tests/integration/_cli2runner.py
  tests/integration/_tmux_session.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run_unicode/base.py
  tests/integration/actions/templar/base.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
  tests/unit/configuration_subsystem/test_settings_sources.py
Labels: skip-changelog

#1519 Update ansible-builder version
  .config/requirements.in
  requirements.txt
Labels: skip-changelog

#1520 Switch to struct data for galaxy
  tests/fixtures/common/builder/test_ee/execution-environment.yml
Labels: skip-changelog

#1522 Test sidecar filter plugin doc
  tests/fixtures/common/collections/ansible_collections/company_name/coll_1/plugins/filter/coll_1.py
  tests/fixtures/common/collections/ansible_collections/company_name/coll_1/plugins/filter/filter_1.yml
  tests/fixtures/integration/actions/doc/test_direct_interactive_ee.py/test/filter_doc_pass/0.json
  tests/fixtures/integration/actions/doc/test_direct_interactive_noee.py/test/filter_doc_pass/0.json
  tests/fixtures/integration/actions/doc/test_stdout.py/test/filter_doc_with_ee/0.json
  tests/fixtures/integration/actions/doc/test_stdout.py/test/filter_doc_without_ee/0.json
  tests/fixtures/integration/actions/doc/test_welcome_interactive_ee.py/test/filter_doc_pass/0.json
  tests/fixtures/integration/actions/doc/test_welcome_interactive_ee.py/test/filter_doc_pass/1.json
  tests/fixtures/integration/actions/doc/test_welcome_interactive_noee.py/test/filter_doc_pass/0.json
  tests/fixtures/integration/actions/doc/test_welcome_interactive_noee.py/test/filter_doc_pass/1.json
  tests/integration/actions/doc/test_direct_interactive_ee.py
  tests/integration/actions/doc/test_direct_interactive_noee.py
  tests/integration/actions/doc/test_stdout.py
  tests/integration/actions/doc/test_welcome_interactive_ee.py
  tests/integration/actions/doc/test_welcome_interactive_noee.py
Labels: enhancement

#1525 Remove need for credentials on pypi publishing
  .github/workflows/release.yml
Labels: skip-changelog

#1530 Update ansible-builder version
  .config/requirements.in
  requirements.txt
Labels: skip-changelog

#1502 DevDocs: building from src and testing process
  .github/CONTRIBUTING.md
  docs/contributing/images/test_tree_view.png
Labels: documentation, developers guide, skip-changelog

#1536 Avoid testing errors caused by declare_namespace
  tests/unit/test_circular_imports.py
Labels: skip-changelog

#1538 Fix building of dynamic configuration section
  .config/dictionary.txt
  .pre-commit-config.yaml
  docs/.generated/.gitignore
  docs/_ext/regenerate_docs.py
  tox.ini
Labels: bug

#1537 Isolate navigator from ansible-runner internal warnings
  pyproject.toml
  src/ansible_navigator/runner/ansible_config.py
  tests/integration/test_stdout_exit_codes.py
Labels: skip-changelog

#1539 Set user to root with podman
  src/ansible_navigator/runner/base.py
Labels: bug
