Repository ansible/ansible-navigator, pull requests merged in 2023-01, with the labels that each got.

#1371 Use dynamic matrix
  .github/workflows/tox.yml
Labels: skip-changelog

#1376 Arrange test-ids to order them correctly
  tests/integration/actions/images/test_direct_interactive_ee.py
  tests/integration/actions/images/test_direct_interactive_noee.py
  tests/integration/actions/images/test_welcome_interactive_ee.py
  tests/integration/actions/images/test_welcome_interactive_noee.py
  tests/integration/actions/inventory/test_direct_interactive_ee.py
  tests/integration/actions/inventory/test_direct_interactive_noee.py
  tests/integration/actions/inventory/test_welcome_interactive_ee.py
  tests/integration/actions/inventory/test_welcome_interactive_noee.py
  tests/integration/actions/run/test_direct_interactive_ee.py
  tests/integration/actions/run/test_direct_interactive_noee.py
  tests/integration/actions/run/test_welcome_interactive_ee.py
  tests/integration/actions/run/test_welcome_interactive_noee.py
  tests/integration/actions/templar/test_direct_interactive_ee.py
  tests/integration/actions/templar/test_direct_interactive_noee.py
  tests/integration/actions/templar/test_welcome_interactive_ee.py
  tests/integration/actions/templar/test_welcome_interactive_noee.py
Labels: skip-changelog

#1382 vim-minimal installs vi
  tests/integration/actions/templar/base.py
Labels: skip-changelog

#1383 Allow fixture update env var
  tests/conftest.py
Labels: impatience-allowed, skip-changelog

#1379 Light-Copy-Edit HM803
  README.md
Labels: documentation, skip-changelog

#1386 Add vscode settings
  .pre-commit-config.yaml
  .vscode/launch.json
  .vscode/settings.json
Labels: skip-changelog

#1391 Mask python version from test fixtures
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/16.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/18.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/22.json
  tests/fixtures/integration/actions/collections/test_direct_interactive_noee.py/test/24.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/17.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/19.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/23.json
  tests/fixtures/integration/actions/collections/test_welcome_interactive_noee.py/test/25.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/1.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/3.json
  tests/fixtures/integration/actions/exec/test_stdout_file.py/test/2.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/7.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/8.json
  tests/integration/_common.py
Labels: skip-changelog

#1390 Avoid importlib contents deprecation
  src/ansible_navigator/actions/_actions.py
Labels: bug

#1392 Mask image ages
  tests/fixtures/integration/actions/exec/test_stdout_file.py/test/2.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/images/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/images/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/5.json
  tests/integration/actions/images/base.py
Labels: impatience-allowed, skip-changelog

#1393 Mask hostname from exec
  tests/fixtures/integration/actions/exec/test_stdout_file.py/test/2.json
  tests/integration/actions/exec/base.py
Labels: tests, impatience-allowed, skip-changelog

#1395 Mask out unicode test fixtures
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/run_unicode/test_direct_interactive_noee.py/test/5.json
  tests/integration/actions/run_unicode/base.py
Labels: impatience-allowed, skip-changelog

#1396 Remove hard coded small image
  src/ansible_navigator/data/images_dockerfile
  tests/conftest.py
  tests/integration/test_execution_environment_image.py
Labels: skip-changelog

#1394 Add more vscode settings
  .vscode/settings.json
Labels: skip-changelog

#1398 Add more configuration entry in vscode settings
  .vscode/launch.json
Labels: skip-changelog

#1404 Ensure tmux is installed for testing
  tests/conftest.py
Labels: tests, skip-changelog

#1403 Exit tests for failed pull
  tests/conftest.py
Labels: tests, skip-changelog

#1405 Run mypy only once
  .pre-commit-config.yaml
Labels: skip-changelog

#1406 Move directory containing theme and terminal colors into the source tree
  .pre-commit-config.yaml
  cspell.config.yaml
  share/ansible_navigator/themes/dark_vs.json
  share/ansible_navigator/themes/terminal_colors.json
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/constants.py
  src/ansible_navigator/data/themes/dark_vs.json
  src/ansible_navigator/data/themes/terminal_colors.json
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/ui_config.py
  src/ansible_navigator/utils/compatibility.py
  src/ansible_navigator/utils/print.py
  tests/unit/ui_framework/test_colorize.py
Labels: bug

#1407 Enable flake8, mypy, and pylint for vscode
  .vscode/settings.json
Labels: skip-changelog

#1408 Move directory containing grammar files into source tree
  .pre-commit-config.yaml
  .prettierignore
  .vscode/settings.json
  cspell.config.yaml
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/constants.py
  src/ansible_navigator/data/grammar/JSON.tmLanguage.json
  src/ansible_navigator/data/grammar/html-derivative.tmLanguage.json
  src/ansible_navigator/data/grammar/html.tmLanguage.json
  src/ansible_navigator/data/grammar/log.tmLanguage.json
  src/ansible_navigator/data/grammar/markdown.tmLanguage.json
  src/ansible_navigator/data/grammar/shell-unix-bash.tmLanguage.json
  src/ansible_navigator/data/grammar/source.json.json
  src/ansible_navigator/data/grammar/source.shell.json
  src/ansible_navigator/data/grammar/source.yaml.json
  src/ansible_navigator/data/grammar/text.html.basic.json
  src/ansible_navigator/data/grammar/text.html.derivative.json
  src/ansible_navigator/data/grammar/text.html.markdown.json
  src/ansible_navigator/data/grammar/text.log.json
  src/ansible_navigator/data/grammar/yaml.tmLanguage.json
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/ui_config.py
  src/ansible_navigator/utils/print.py
  tests/unit/ui_framework/test_colorize.py
Labels: bug

#1409 Use a valid container engine in exit code tests
  tests/integration/test_stdout_exit_codes.py
Labels: tests, impatience-allowed, skip-changelog

#1410 Improve session setup
  tests/integration/_tmux_session.py
Labels: skip-changelog

#1411 Provide a tty for stdout subprocess doc tests
  tests/conftest.py
  tests/integration/actions/doc/test_stdout_subprocess.py
Labels: skip-changelog

#1412 Check config.label key
  src/ansible_navigator/actions/images.py
Labels: skip-changelog

#1377 Add doc about debugging ansible-navigator
  .github/CONTRIBUTING.md
Labels: documentation, skip-changelog

#1413 Run stdout exit code test with a TTY
  tests/integration/test_stdout_exit_codes.py
Labels: impatience-allowed, skip-changelog

#1414 Suggest a fetch all for settings migration test
  tests/integration/version_migration/test_v1_v2_settings.py
Labels: skip-changelog

#1416 Ensure volume mounted collections are identified as `bind_mount`
  src/ansible_navigator/actions/collections.py
Labels: bug

#1420 Add json output for collections subcommand
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/data/settings-sample.template.yml
  src/ansible_navigator/data/settings-schema.partial.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/_interactions.py
  tests/integration/actions/collections/test_stdout_tmux.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/settings/test_direct_interactive_ee.py
  tests/integration/actions/settings/test_direct_interactive_noee.py
  tests/integration/actions/settings/test_welcome_interactive_ee.py
  tests/integration/actions/settings/test_welcome_interactive_noee.py
  tests/unit/configuration_subsystem/data.py
Labels: enhancement

#1422 Replace collection stdout tests
  src/ansible_navigator/configuration_subsystem/definitions.py
  tests/conftest.py
  tests/defaults.py
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/0.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/1.json
  tests/fixtures/integration/actions/collections/test_stdout_tmux.py/test/2.json
  tests/integration/_common.py
  tests/integration/_tmux_session.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/collections/test_mode_stdout.py
  tests/integration/actions/collections/test_stdout_tmux.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/exec/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/lint/base.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run_unicode/base.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
  tests/integration/conftest.py
  tests/integration/version_migration/test_v1_v2_settings.py
Labels: skip-changelog

#1423 Add isort on save to vscode settings
  .vscode/settings.json
Labels: skip-changelog

#1424 Type and lint tests/conftest.py
  .flake8
  tests/conftest.py
Labels: skip-changelog

#1425 Add format to schema
  src/ansible_navigator/data/ansible-navigator.json
Labels: skip-changelog

#1426 Enable tox-extra
  tox.ini
Labels: skip-changelog

#1427 Type hint and lint `tests/integration/conftest.py`
  .flake8
  tests/integration/conftest.py
Labels: skip-changelog

#1428 Type hint and lint `tests/integration/_common.py`
  .flake8
  tests/integration/_common.py
Labels: skip-changelog
