Repository ansible/ansible-navigator, pull requests merged in 2023-04, with the labels that each got.

#1478 Require py3.9 or later
  pyproject.toml
Labels: bug

#1486 Fix readthedocs links
  README.md
Labels: documentation, skip-changelog

#1488 Re-enable builder tests
  tests/integration/actions/builder/test_stdout_tmux.py
Labels: skip-changelog

#1474 Allow extra parameters when playbook is defined in configuration/settings file
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  tests/unit/actions/test_exec.py
  tests/unit/test_cli.py
Labels: bug

#1492 Add configuration entry for images, lint and run subcommands in vscode settings
  .vscode/launch.json
Labels: documentation, developers guide, skip-changelog

#1494 Adjust Docs For Ansible Vault
  docs/faq.md
Labels: documentation, bug, skip-changelog

#1496 Fix for exec
  src/ansible_navigator/actions/exec.py
Labels: bug

#1497 Remove `isort` in favor of `ruff`
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_navigator/action_base.py
  src/ansible_navigator/action_runner.py
  src/ansible_navigator/actions/help_doc.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/log.py
  src/ansible_navigator/actions/serialize_yaml.py
  src/ansible_navigator/actions/settings.py
  src/ansible_navigator/actions/write_file.py
  src/ansible_navigator/ui_framework/form_utils.py
  tests/conftest.py
  tests/integration/actions/collections/test_mode_stdout.py
  tests/integration/actions/doc/test_stdout_subprocess.py
  tests/integration/actions/images/test_stdout_tmux.py
  tests/integration/actions/lint/test_stdout_tmux.py
  tests/integration/conftest.py
  tests/integration/settings_from_cli/test_json_schema_errors.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
  tests/integration/test_stdout_exit_codes.py
  tests/unit/actions/run/test_artifact.py
  tests/unit/actions/run/test_runner_async.py
  tests/unit/actions/settings/test_settings.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/post_processors/test_execution_environment_volume_mounts.py
  tests/unit/configuration_subsystem/post_processors/test_playbook_artifact_save_as.py
  tests/unit/configuration_subsystem/post_processors/test_time_zone.py
  tests/unit/configuration_subsystem/test_entries_sanity.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
  tests/unit/configuration_subsystem/test_internals.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_json_schema.py
  tests/unit/configuration_subsystem/test_mode_subcommand_action.py
  tests/unit/configuration_subsystem/test_navigator_post_processor.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_presentable.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
  tests/unit/logger/test_append.py
  tests/unit/logger/test_time_zone.py
  tests/unit/test_cli.py
  tests/unit/utils/test_dot_paths.py
  tests/unit/utils/test_serialize_dataclass.py
  tests/unit/utils/test_unserializable.py
Labels: skip-changelog

#1499 Fix issues while cataloging collections
  .vscode/launch.json
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/data/catalog_collections.py
Labels: bug

#1500 Improve type hinting
  pyproject.toml
  src/ansible_navigator/tm_tokenize/compiler.py
  src/ansible_navigator/tm_tokenize/grammars.py
  src/ansible_navigator/tm_tokenize/reg.py
  src/ansible_navigator/tm_tokenize/region.py
  src/ansible_navigator/tm_tokenize/rules.py
  src/ansible_navigator/tm_tokenize/state.py
  src/ansible_navigator/tm_tokenize/tokenize.py
  src/ansible_navigator/tm_tokenize/utils.py
  src/ansible_navigator/utils/json_schema.py
  tests/smoke/no_test_dependencies.py
Labels: skip-changelog

#1503 Compatibility with ansible-builder v3
  .config/requirements.in
  .gitignore
  .vscode/settings.json
  requirements.txt
  src/ansible_navigator/data/ansible-navigator.json
  tests/conftest.py
  tests/fixtures/common/builder/test_ee/context/.gitignore
  tests/fixtures/common/builder/test_ee/execution-environment.yml
  tests/fixtures/common/builder/test_ee/requirements.yml
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/builder/test_stdout_tmux.py/test/7.json
  tests/integration/actions/builder/base.py
  tests/integration/actions/builder/test_stdout_tmux.py
Labels: enhancement, impatience-allowed
