Repository ansible/ansible-navigator, pull requests merged in 2023-07, with the labels that each got.

#1570 Update dependencies
  requirements.txt
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/13.json
Labels: skip-changelog

#1572 suggested cleanups for vault password faq entry
  docs/faq.md
Labels: documentation, skip-changelog

#1569 More cleanup of image_introspect
  src/ansible_navigator/data/image_introspect.py
Labels: skip-changelog

#1576 Add EE Getting started references to docs
  docs/faq.md
  docs/index.md
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
Labels: documentation, bug

#1578 Check for ansible-lint version if not using an EE
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
Labels: skip-changelog

#1581 Add ansible-lint as a requirement
  .config/requirements.in
  requirements.txt
Labels: skip-changelog

#1585 Fix image introspect for PythonPackages
  src/ansible_navigator/data/image_introspect.py
Labels: bug

#1587 Change the python_exec path to /usr/bin/python3
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/data/image_introspect.py
Labels: bug
