Repository ansible/ansible-navigator, pull requests merged in 2023-03, with the labels that each got.

#1449 Remove check for virtualenv presence
  tests/conftest.py
Labels: skip-changelog

#1455 Remove 3.8 tests
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#1456 Down version for select deps
  requirements.txt
Labels: skip-changelog

#1458 Remove dep on pkg_resources, ignore runner err
  setup.cfg
  src/ansible_navigator/cli.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/utils/compatibility.py
  src/ansible_navigator/version.py
  tests/unit/test_circular_imports.py
Labels: skip-changelog

#1430 Faq docs updates for `enable_prompts`
  docs/faq.md
Labels: documentation, skip-changelog

#1433 Add json output for images subcommand
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  tests/fixtures/integration/actions/images/test_stdout_tmux.py/test/4.json
  tests/integration/actions/images/test_stdout_tmux.py
Labels: enhancement

#1453 Drop python 3.8 support
  .github/workflows/release.yml
  .pre-commit-config.yaml
  docs/faq.md
  requirements.txt
  setup.cfg
  share/ansible_navigator/utils/catalog_collections.py
  src/ansible_navigator/action_base.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/constants.py
  src/ansible_navigator/content_defs.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/introspect.py
  src/ansible_navigator/logger.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/tm_tokenize/_types.py
  src/ansible_navigator/tm_tokenize/compiler.py
  src/ansible_navigator/tm_tokenize/reg.py
  src/ansible_navigator/tm_tokenize/region.py
  src/ansible_navigator/tm_tokenize/rules.py
  src/ansible_navigator/tm_tokenize/utils.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/curses_defs.py
  src/ansible_navigator/ui_framework/form_defs.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/ui_config.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/utils/compatibility.py
  src/ansible_navigator/utils/dict_merge.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/functions.py
  src/ansible_navigator/utils/key_value_store.py
  src/ansible_navigator/utils/packaged_data.py
  src/ansible_navigator/utils/version_migration/definitions.py
  tests/conftest.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/exec/base.py
  tests/integration/conftest.py
  tests/unit/actions/run/test_artifact.py
  tests/unit/logger/test_time_zone.py
  tests/unit/test_circular_imports.py
  tests/unit/utils/conftest.py
  tests/unit/utils/test_dot_paths.py
  tests/unit/utils/test_serialize_dataclass.py
Labels: major

#1431 Move `help_playbook` logic from actions to its post-processor
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  tests/unit/actions/run/test_artifact.py
Labels: skip-changelog

#1436 CommandAsync should not discard event
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/navigator_configuration.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/data/ansible-navigator.json
  src/ansible_navigator/data/settings-sample.template.yml
  src/ansible_navigator/data/settings-schema.partial.json
  src/ansible_navigator/runner/command_async.py
  tests/fixtures/integration/actions/lint/test_direct_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_ee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/settings/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/2.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/3.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/4.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/5.json
  tests/fixtures/integration/actions/settings/test_stdout_tmux.py/test/6.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_ee.py/test/9.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/settings/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/unit/configuration_subsystem/ansible-navigator.yml
  tests/integration/actions/settings/base.py
  tests/integration/actions/settings/test_direct_interactive_ee.py
  tests/integration/actions/settings/test_direct_interactive_noee.py
  tests/integration/actions/settings/test_welcome_interactive_ee.py
  tests/integration/actions/settings/test_welcome_interactive_noee.py
  tests/unit/actions/run/test_runner_async.py
  tests/unit/configuration_subsystem/data.py
Labels: bug

#1440 Add support to direct access a playbook provided by a collection for :run subcommand
  .config/dictionary.txt
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/utils/functions.py
  tests/fixtures/common/collections/ansible_collections/company_name/coll_1/playbooks/playbook_1.yaml
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/0.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/1.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/10.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/11.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/12.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/13.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/2.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/3.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/4.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/5.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/6.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/7.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/8.json
  tests/fixtures/integration/actions/run/test_direct_interactive_ee_collection.py/test/9.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/0.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/1.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/10.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/11.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/12.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/13.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/2.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/3.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/4.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/5.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/6.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/7.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/8.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/9.json
  tests/integration/actions/run/base.py
  tests/integration/actions/run/test_direct_interactive_ee_collection.py
  tests/integration/actions/run/test_direct_interactive_noee_collection.py
Labels: bug

#1461 More pkg_resource deprecation warnings
  tests/unit/test_circular_imports.py
Labels: impatience-allowed, skip-changelog

#1464 Add docstrings, type hints to configuration subsystem tests (D/DAR)
  .flake8
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_broken_settings.py
  tests/unit/configuration_subsystem/test_entries_sanity.py
  tests/unit/configuration_subsystem/test_fixture_sanity.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_mode_subcommand_action.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/configuration_subsystem/test_previous_cli.py
  tests/unit/configuration_subsystem/test_sample_configurations.py
  tests/unit/configuration_subsystem/utils.py
Labels: documentation, tests, skip-changelog

#1468 Adopt PEP-621 packaging
  .config/requirements-docs.txt
  .config/requirements-test.txt
  .config/requirements.in
  MANIFEST.in
  pyproject.toml
  setup.cfg
Labels: bug

#1472 Update schema
  src/ansible_navigator/data/ansible-navigator.json
  tests/integration/version_migration/test_v1_v2_settings.py
Labels: bug, impatience-allowed
