Repository ansible/ansible-navigator, pull requests merged in 2023-09, with the labels that each got.

#1601 Remove the deprecated sys_packages key from configuration
  .readthedocs.yml
Labels: skip-changelog

#1600 Contributing guidelines: improve
  .github/CONTRIBUTING.md
  README.md
Labels: documentation, skip-changelog

#1608 Update ansible-lint to 6.19.0
  .config/requirements.in
  requirements.txt
Labels: skip-changelog

#1574 Add tests for `lint`, without an EE
  tests/fixtures/integration/actions/lint/test_direct_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_noee.py/test/0.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_noee.py/test/1.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/lint/test_welcome_interactive_noee.py/test/3.json
  tests/integration/actions/collections/test_direct_interactive_noee.py
  tests/integration/actions/lint/test_direct_interactive_noee.py
  tests/integration/actions/lint/test_welcome_interactive_noee.py
Labels: bug

#1590 Expand env variable mentioned in the pull arguments (--pa)
  src/ansible_navigator/image_manager/puller.py
  tests/unit/image_manager/test_image_puller.py
Labels: bug

#1617 upgrade codecov-action from `v3` to `v4`
  .github/workflows/tox.yml
Labels: skip-changelog
