Repository ansible/ansible-navigator, pull requests merged in 2023-06, with the labels that each got.

#1549 Fix the broken VSCode test tree link in Contributing Guidelines
  .github/images/test_tree_view.png
  docs/index.md
Labels: skip-changelog

#1547 DevDocs: Overview of base entry points and summary of src files
  .github/CONTRIBUTING.md
Labels: documentation, developers guide, skip-changelog

#1560 fix vault file with env var
  .config/dictionary.txt
  docs/faq.md
Labels: documentation, skip-changelog
