Repository ansible/ansible-navigator, pull requests merged in 2024-03, with the labels that each got.

#1706 pytest: remove flaky reruns
  tests/integration/actions/images/test_direct_interactive_noee.py
  tests/integration/actions/lint/base.py
  tests/integration/actions/run_unicode/base.py
  tests/unit/logger/test_time_zone.py
Labels: skip-changelog

#1707 pytest: improve logging and reliability
  .config/constraints.txt
  .config/dictionary.txt
  .config/requirements-test.in
  pyproject.toml
  src/ansible_navigator/ui_framework/menu_builder.py
  tests/conftest.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/collections/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/doc/test_stdout_subprocess.py
  tests/integration/actions/exec/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/lint/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run_unicode/base.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
  tests/integration/diagnostics/test_from_cli.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
  tests/unit/utils/test_functions.py
  tox.ini
Labels: skip-changelog

#1704 More types (2)
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/utils/functions.py
Labels: skip-changelog

#1703 More types
  pyproject.toml
  src/ansible_navigator/initialization.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_handler_working.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/utils/version_migration/definitions.py
  tests/conftest.py
Labels: skip-changelog

#1708 More types
  .pre-commit-config.yaml
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/tm_tokenize/_types.py
  src/ansible_navigator/ui_framework/__init__.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/utils/json_schema.py
  src/ansible_navigator/utils/key_value_store.py
  src/ansible_navigator/utils/serialize.py
  tests/fixtures/integration/actions/inventory/using_plugin/collections/ansible_collections/test/test/plugins/inventory/test.py
  tests/integration/_action_run_test.py
  tests/integration/_common.py
  tests/integration/_tmux_session.py
  tests/integration/test_stdout_exit_codes.py
  tests/unit/configuration_subsystem/conftest.py
  tests/unit/configuration_subsystem/test_container_engine_auto.py
  tests/unit/configuration_subsystem/test_entries_sanity.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/test_navigator_post_processor.py
  tests/unit/configuration_subsystem/test_precedence.py
  tests/unit/test_cli.py
  tests/unit/ui_framework/test_colorize.py
  tests/unit/utils/test_serialize_yaml.py
  tests/unit/utils/test_unserializable.py
Labels: skip-changelog

#1711 Update ack.yml
  .github/workflows/ack.yml
Labels: skip-changelog

#1714 Improve the FAQ on how to use ansible vaults with ansible-navigator
  docs/faq.md
Labels: documentation, skip-changelog

#1716 drop setuptools_scm_git_archive
  pyproject.toml
Labels: bug

#1723 Improve test failure for time_zone
  tests/unit/logger/test_time_zone.py
Labels: skip-changelog

#1725 Collect pytest logs
  .config/constraints.txt
  .github/workflows/tox.yml
Labels: skip-changelog

#1724 test: ignore empty /etc/ansible/ansible.cfg file
  tests/conftest.py
Labels: skip-changelog

#1719 Suggest adt installation
  .config/constraints.txt
  .config/requirements-docs.in
  .pre-commit-config.yaml
  .readthedocs.yml
  .vscode/settings.json
  docs/installation.md
  mkdocs.yml
  tox.ini
Labels: documentation, skip-changelog
