Repository ansible/ansible-navigator, pull requests merged in 2024-02, with the labels that each got.

#1665 Switch from darglint to pydoclint
  .pre-commit-config.yaml
  pyproject.toml
  src/ansible_navigator/data/ansible-navigator.json
  tests/integration/version_migration/test_v1_v2_settings.py
Labels: skip-changelog

#1668 Fix some of the duplicate test names
  tests/unit/actions/test_config.py
  tests/unit/configuration_subsystem/post_processors/test_playbook_artifact_save_as.py
  tests/unit/configuration_subsystem/test_settings_effective.py
  tests/unit/logger/test_append.py
  tests/unit/logger/test_time_zone.py
Labels: skip-changelog

#1673 Update pytest-plus to 0.6.1
  .config/requirements-test.txt
  pyproject.toml
  requirements.txt
Labels: skip-changelog

#1667 Review codecov configuration
  .github/workflows/tox.yml
  codecov.yml
Labels: skip-changelog

#1678 Auto-retry tests that fail randomly
  .config/requirements-test.txt
  .vscode/settings.json
  requirements.txt
  tests/integration/actions/images/test_direct_interactive_noee.py
  tests/integration/actions/lint/base.py
  tests/integration/actions/run_unicode/base.py
  tests/unit/logger/test_time_zone.py
  tox.ini
Labels: skip-changelog

#1670 Drop support to Python 3.9
  .config/requirements-test.txt
  .config/requirements.in
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .gitignore
  .pre-commit-config.yaml
  docs/faq.md
  docs/installation.md
  pyproject.toml
  src/ansible_navigator/action_defs.py
  src/ansible_navigator/actions/__init__.py
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/exec.py
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/app_public.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/content_defs.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_curses_information.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_defs.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/utils/compatibility.py
  src/ansible_navigator/utils/dict_merge.py
  src/ansible_navigator/utils/functions.py
  src/ansible_navigator/utils/serialize.py
  src/ansible_navigator/utils/version_migration/definitions.py
  tests/integration/_action_run_test.py
  tests/integration/_common.py
  tests/unit/configuration_subsystem/test_entries_sanity.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
  tests/unit/utils/test_serialize_dataclass.py
  tox.ini
Labels: enhancement

#1674 Update dependencies
  requirements.txt
Labels: skip-changelog

#1669 Fixes for new mkdocs-ansible branding
  .config/requirements-docs.txt
  docs/index.md
  mkdocs.yml
Labels: skip-changelog, dependencies

#1661 Drop the venv requirement from running tests
  .envrc
  .gitignore
  tests/conftest.py
  tests/integration/_tmux_session.py
  tests/integration/actions/doc/test_stdout_subprocess.py
  tests/integration/diagnostics/test_from_cli.py
  tests/integration/settings_from_cli/test_json_schema_errors.py
  tests/integration/test_stdout_exit_codes.py
  tests/integration/version_migration/test_v1_v2_settings.py
  tests/smoke/no_test_dependencies.py
  tests/unit/configuration_subsystem/post_processors/test_inventory.py
  tests/unit/configuration_subsystem/test_ansible_config_parse.py
Labels: skip-changelog

#1685 Prevent accidental use of incompatible libtmux
  .config/requirements-test.txt
Labels: skip-changelog

#1662 Improve test execution on macos (tmux)
  pyproject.toml
  tests/integration/_tmux_session.py
  tox.ini
Labels: skip-changelog

#1682 Review requirements file into new unified structure
  .config/constraints.txt
  .config/requirements-docs.in
  .config/requirements-test.in
  .github/dependabot.yml
  pyproject.toml
  tox.ini
Labels: skip-changelog

#1689 Resolve mypy disallow_any_generics
  pyproject.toml
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/utils.py
  src/ansible_navigator/content_defs.py
  src/ansible_navigator/data/catalog_collections.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/runner/ansible_doc.py
  src/ansible_navigator/runner/ansible_inventory.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/runner/command_base.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/field_button.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_curses_information.py
  src/ansible_navigator/ui_framework/field_information.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/field_text.py
  src/ansible_navigator/ui_framework/field_working.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_handler_button.py
  src/ansible_navigator/ui_framework/form_handler_information.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_handler_working.py
  src/ansible_navigator/ui_framework/form_utils.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/ui_framework/validators.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/functions.py
  src/ansible_navigator/utils/serialize.py
  src/ansible_navigator/utils/version_migration/definitions.py
  src/ansible_navigator/utils/version_migration/settings_file.py
  src/ansible_navigator/utils/version_migration/v1_v2_settings_file.py
  tests/integration/_common.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
  tests/unit/utils/test_dot_paths.py
  tests/unit/utils/test_functions.py
  tests/unit/utils/test_serialize_dataclass.py
Labels: skip-changelog

#1690 mypy: address disallow_untyped_calls
  .flake8
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/image_manager/puller.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/utils/ansi.py
  src/ansible_navigator/utils/functions.py
Labels: skip-changelog

#1691 More types
  pyproject.toml
  src/ansible_navigator/actions/_actions.py
  src/ansible_navigator/actions/inventory.py
  src/ansible_navigator/actions/run.py
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/diagnostics.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/utils/version_migration/settings_file.py
  tests/conftest.py
  tests/fixtures/common/collections/ansible_collections/company_name/coll_1/plugins/filter/coll_1.py
  tests/integration/actions/builder/base.py
  tests/integration/actions/config/base.py
  tests/integration/actions/doc/base.py
  tests/integration/actions/images/base.py
  tests/integration/actions/inventory/base.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
  tests/integration/test_execution_environment.py
  tests/integration/test_execution_environment_image.py
  tests/integration/test_pass_environment_variable.py
  tests/integration/test_set_environment_variable.py
  tests/unit/actions/collections/test_collection_doc_cache_path.py
  tests/unit/actions/run/test_artifact.py
  tests/unit/actions/run/test_runner_async.py
  tests/unit/actions/settings/test_settings.py
  tests/unit/actions/test_config.py
  tests/unit/actions/test_exec.py
  tests/unit/actions/test_inventory.py
  tests/unit/configuration_subsystem/test_internals.py
  tests/unit/configuration_subsystem/test_settings_effective.py
  tests/unit/configuration_subsystem/test_settings_sources.py
  tests/unit/image_manager/test_image_puller.py
  tests/unit/logger/test_append.py
  tests/unit/logger/test_time_zone.py
  tests/unit/test_cli.py
  tests/unit/test_image_introspection.py
Labels: skip-changelog

#1692 More types
  src/ansible_navigator/actions/config.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/steps.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_handler_button.py
  src/ansible_navigator/ui_framework/form_handler_options.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/utils/version_migration/definitions.py
  tests/smoke/no_test_dependencies.py
  tests/unit/configuration_subsystem/post_processors/test_execution_environment_volume_mounts.py
Labels: skip-changelog

#1699 Update dependencies
  .config/constraints.txt
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/10.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/2.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/4.json
  tests/fixtures/integration/actions/run/test_direct_interactive_noee_collection.py/test/8.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/run/test_welcome_interactive_noee.py/test/9.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/10.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/4.json
  tests/fixtures/integration/actions/templar/test_direct_interactive_noee.py/test/8.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/11.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/5.json
  tests/fixtures/integration/actions/templar/test_welcome_interactive_noee.py/test/9.json
Labels: skip-changelog

#1700 Address pytest-plus test id regex
  .vscode/settings.json
  pyproject.toml
  tests/integration/_interactions.py
  tests/integration/actions/doc/test_direct_interactive_ee.py
  tests/integration/actions/doc/test_direct_interactive_noee.py
  tests/integration/actions/doc/test_stdout.py
  tests/integration/actions/doc/test_welcome_interactive_ee.py
  tests/integration/actions/doc/test_welcome_interactive_noee.py
  tests/integration/actions/images/test_stdout_tmux.py
  tests/integration/actions/lint/test_stdout_tmux.py
  tests/integration/actions/replay/test_direct_interactive_ee.py
  tests/integration/actions/replay/test_direct_interactive_noee.py
  tests/integration/actions/replay/test_welcome_interactive_ee.py
  tests/integration/actions/replay/test_welcome_interactive_noee.py
  tests/integration/actions/stdout/test_direct_interactive_ee.py
  tests/integration/actions/stdout/test_direct_interactive_noee.py
  tests/integration/actions/stdout/test_welcome_interactive_ee.py
  tests/integration/actions/stdout/test_welcome_interactive_noee.py
  tests/unit/configuration_subsystem/test_navigator_post_processor.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
  tests/unit/utils/test_functions.py
Labels: skip-changelog

#1701 More types
  src/ansible_navigator/actions/open_file.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/utils/definitions.py
  tests/integration/actions/replay/base.py
  tests/integration/actions/run/base.py
  tests/integration/actions/run/test_stdout_tmux.py
  tests/integration/actions/run_unicode/base.py
  tests/integration/actions/run_unicode/test_stdout_tmux.py
  tests/integration/actions/settings/base.py
  tests/integration/actions/stdout/base.py
  tests/integration/actions/templar/base.py
  tests/integration/version_migration/test_v1_v2_settings.py
Labels: skip-changelog

#1702 More types
  src/ansible_navigator/command_runner/command_runner.py
  src/ansible_navigator/configuration_subsystem/definitions.py
  src/ansible_navigator/configuration_subsystem/defs_presentable.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/configuration_subsystem/parser.py
  src/ansible_navigator/configuration_subsystem/utils.py
  src/ansible_navigator/content_defs.py
  src/ansible_navigator/data/image_introspect.py
  src/ansible_navigator/image_manager/inspector.py
  src/ansible_navigator/runner/command_async.py
  src/ansible_navigator/runner/command_base.py
  src/ansible_navigator/ui_framework/curses_window.py
  src/ansible_navigator/ui_framework/field_checks.py
  src/ansible_navigator/ui_framework/field_radio.py
  src/ansible_navigator/ui_framework/form.py
  src/ansible_navigator/ui_framework/form_handler_button.py
  src/ansible_navigator/ui_framework/form_handler_information.py
  src/ansible_navigator/ui_framework/form_handler_text.py
  src/ansible_navigator/ui_framework/menu_builder.py
  src/ansible_navigator/ui_framework/sentinels.py
  src/ansible_navigator/ui_framework/ui.py
  src/ansible_navigator/ui_framework/utils.py
  src/ansible_navigator/ui_framework/validators.py
  src/ansible_navigator/utils/definitions.py
  src/ansible_navigator/utils/dot_paths.py
  src/ansible_navigator/utils/json_schema.py
  src/ansible_navigator/utils/print.py
  src/ansible_navigator/utils/serialize.py
  src/ansible_navigator/utils/version_migration/settings_file.py
  tests/fixtures/integration/actions/inventory/using_plugin/collections/ansible_collections/test/test/plugins/inventory/test.py
  tests/integration/_common.py
  tests/integration/diagnostics/test_from_cli.py
  tests/integration/settings_from_cli/test_json_schema_errors.py
  tests/smoke/no_test_dependencies.py
  tests/unit/configuration_subsystem/test_container_engine_auto.py
  tests/unit/configuration_subsystem/test_navigator_post_processor.py
  tests/unit/configuration_subsystem/test_posix_message_queue.py
  tests/unit/configuration_subsystem/test_settings_sample.py
  tests/unit/test_typestep.py
  tests/unit/ui_framework/test_colorize.py
  tests/unit/utils/test_dockerfile.py
  tests/unit/utils/test_dot_paths.py
  tests/unit/utils/test_functions.py
  tests/unit/utils/test_serialize_dataclass.py
  tests/unit/utils/test_unserializable.py
Labels: skip-changelog

#1705 gha: enable pip cache
  .github/workflows/tox.yml
Labels: skip-changelog
