Repository ansible/ansible-navigator, pull requests merged in 2024-07, with the labels that each got.

#1810 Exit with an appropriate message if the image is invalid
  src/ansible_navigator/cli.py
Labels: bug

#1817 Updated cspell dictionary and removed unneeded values
  .config/dictionary.txt
Labels: minor

#1823 chore: Update .sonarcloud.properties
  .sonarcloud.properties
Labels: skip-changelog

#1824 chore: Update .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: skip-changelog

#1825 chore: Update .github/CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#1826 chore: Update .vscode/extensions.json
  .vscode/extensions.json
Labels: skip-changelog
