Repository ansible/ansible-navigator, pull requests merged in 2024-09, with the labels that each got.

#1846 Fix upload-artifact action to work with v4.4 and newer
  .github/workflows/tox.yml
Labels: bug

#1843 Community comms
  README.md
  docs/contributing/code-of-conduct.md
  docs/contributing/community.md
  docs/index.md
  mkdocs.yml
Labels: documentation, enhancement

#1851 Docs: change Getting started EE guide reference to point to the relevant location
  docs/faq.md
  docs/index.md
Labels: skip-changelog
