Repository ansible/ansible-navigator, pull requests merged in 2025-05, with the labels that each got.

#1979 Improve path normalization with a fallback for non-existent paths
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
Labels: bug

#1986 Ignore the untracked files in the codecov scan
  codecov.yml
Labels: skip-changelog

#1988 chore: Fix codecov use_oidc setting
  .github/workflows/tox.yml
Labels: skip-changelog

#1983 Add merge_group handler for tox workflow
  .github/workflows/tox.yml
Labels: patch

#1994 Update dependencies
  .config/constraints.txt
Labels: dependencies, chore
