Repository ansible/ansible-navigator, pull requests merged in 2025-04, with the labels that each got.

#1939 Fix the lint subcommand failure: (KeyError: 'lines')
  src/ansible_navigator/actions/lint.py
Labels: bug

#1944 Log and ignore malformed plugin doc string.
  src/ansible_navigator/actions/collections.py
Labels: bug

#1942 Isolate testing from content in user ~/.ansible folder
  .env
  .envrc
  .gitignore
  ansible.cfg
  tests/conftest.py
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/0.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/2.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee.py/test/6.json
  tests/fixtures/integration/actions/config/test_direct_interactive_ee_using_cfg.py/test/1.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/2.json
  tests/fixtures/integration/actions/config/test_direct_interactive_noee.py/test/6.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_ee.py/test/7.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/3.json
  tests/fixtures/integration/actions/config/test_welcome_interactive_noee.py/test/7.json
  tests/integration/_common.py
  tests/integration/actions/config/base.py
  tests/unit/configuration_subsystem/test_ansible_config_parse.py
Labels: skip-changelog

#1953 Increase container engine timeout
  tests/conftest.py
Labels: skip-changelog

#1959 Correct toml-sort-fix configuration
  .taplo.toml
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
Labels: skip-changelog

#1960 Normalize ansible config path
  pyproject.toml
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
Labels: bug

#1964 Make coverage file number check a warning
  .github/workflows/tox.yml
Labels: skip-changelog

#1962 Enable uv support during testing
  .config/constraints.txt
  pyproject.toml
  tox.ini
Labels: skip-changelog, dependencies

#1965 Replace black with ruff-format
  .github/CONTRIBUTING.md
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  docs/_ext/regenerate_docs.py
  pyproject.toml
  src/ansible_navigator/actions/lint.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/configuration_subsystem/configurator.py
  src/ansible_navigator/configuration_subsystem/navigator_post_processor.py
  src/ansible_navigator/data/catalog_collections.py
  src/ansible_navigator/runner/base.py
  src/ansible_navigator/ui_framework/colorize.py
  src/ansible_navigator/ui_framework/ui.py
  tests/conftest.py
  tests/integration/_common.py
  tests/integration/version_migration/test_v1_v2_settings.py
  tests/unit/configuration_subsystem/test_container_engine_auto.py
  tests/unit/configuration_subsystem/test_invalid_params.py
  tests/unit/configuration_subsystem/utils.py
  tests/unit/test_circular_imports.py
  tests/unit/test_image_introspection.py
Labels: skip-changelog

#1963 Isolate navigator tests from user configuration
  .env
  tests/conftest.py
Labels: bug

#1968 Add a new script to fetch latest installed python version
  src/ansible_navigator/actions/collections.py
  src/ansible_navigator/actions/images.py
  src/ansible_navigator/cli.py
  src/ansible_navigator/data/python_latest.sh
Labels: bug

#1971 Add `contents:read` permissions to tox workflow
  .github/workflows/tox.yml
Labels: bug
